### ISSUE TITLE
can not load the template 

### ISSUE THREAD

**Issue by archonwang** [akiko-pusu/redmine_issue_templates#11]
when create new issue , I can not use the global issue template with errors

> F, [2016-06-08T20:47:58.748026 #5577] FATAL -- : 
> ActiveRecord::RecordNotFound (Couldn't find IssueTemplate with 'id'=1):
>   plugins/redmine_issue_templates/app/controllers/issue_templates_controller.rb:81:in `load'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
> 

could you please help me, Thanks so much.

my enviroment is 
Redmine 3.2.3 with mysql. and rails 4.2.x
I do not know what happened. but I used it correctly with previous version.

**Comment by akiko-pusu** [comment]
Hi, Steven.
Thanks for your trying this plugin which hosted by Github repository.
Since this repository is preparing to migrate from Bitbucket and under refactoring, that code is not stable. Sorry to bother you.

Could you please try commit: a6699a0cac or master branch  if you hope to clone this plugin from Github.

**Comment by archonwang** [comment]
@akiko-pusu ，  I will test it ASAP. 

Thanks so much.

**Comment by archonwang** [comment]
@akiko-pusu , I tested it in my environment and unfortunately it still not work.
I used branch master, and the error message is 

> F, [2016-06-11T09:43:55.631142 #6684] FATAL -- : 
> ActiveRecord::RecordNotFound (Couldn't find IssueTemplate with 'id'=1):
>   plugins/redmine_issue_templates/app/controllers/issue_templates_controller.rb:87:in `load'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'

my environment is redmine 3.2.3 with mysql, rails 4.2.x, ruby 2.2.x
or if you need more information, I will try to catch more details. 
Thanks so much.

**Comment by akiko-pusu** [comment]
@archonwang 
I’ve just fixed it because JS sets wrong css selector. Please try again if you have time.
Feedback will be appreciated.

**Comment by archonwang** [comment]
@akiko-pusu ,Thanks. Now it works in my environment. 

```
Environment:
  Redmine version                3.2.3.stable.15495
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2
```

PS: In global issue template page, when I create a new template it shows warning information, please check it if you have time to do so. The warning will not influence the function of the plugin at present. 

> W, [2016-06-11T12:47:54.683757 #8882]  WARN -- : WARNING: Can't mass-assign protected attributes for GlobalIssueTemplate: tracker
>         plugins/redmine_issue_templates/app/controllers/global_issue_templates_controller.rb:31:in `new'
>         lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by archonwang** [comment]
Nice. it tested OK。Thanks.
