### ISSUE TITLE
Templates vanished

### ISSUE THREAD

**Issue by ChrisR48** [akiko-pusu/redmine_issue_templates#115]
Hi,

first of all thank you very much for this plugin it is really great.

I created 4 different templates each on for a single tracker. The templates are placed in one project and subprojects inherit these templates.

Now the problem is, that 2 of the 4 templates have vanished. They are not selectable anymore and also are not listed in the configurtion.

As i am the only administrator i would sugest that they are not deleted by accident. Any idea what the problem might be or where i can search?

Best regards Christian

System Setup:

```
Environment:
  Redmine version           3.1.0.stable.14520
  Ruby version                 2.2.1-p85 (2015-02-26) [x86_64-linux]
  Rails version                  4.2.3
  Environment                 production
  Database adapter         Mysql2         
Redmine plugins:
  redmine_issue_templates        0.1.4
```

**Comment by akiko-pusu** [comment]
@ChrisR48, Thanks for using my plugin, and sorry to trouble you.

> Now the problem is, that 2 of the 4 templates have vanished.
> They are not selectable anymore and also are not listed in the configurtion.
Ok, did you upgrade or migrate Redmine and plugin just before templates vanished?

And could you find all the template at http://YOUR_REDMINE_SITE/projects/issue_templates/ ?

> Any idea what the problem might be or where i can search?

If you didn’t remove 2 templates explicitly, they may be still stored in the table.
Can you access your production database? If you could, please see the table named “issue_templates”.

**Comment by ChrisR48** [comment]
Hi,

thank you for your replay. Great!

* There was no update or something else since install of the plugin.
* the projects/issue_templates url produces a 404 not found error
* i checked the database but there are only the templates that are visible in redmine. So the ones i am search are also missing in the database

I am not sure how it happend that the templates were deleted but it seams like they were. May there be a permission issue or something like this.

It is not a big problem as i have a backup for the templates and they are also not this important. I am just wondering why they are gone now.

Do you have any idea what we can do to have more information when this happens again?

Best regards

Christian

**Comment by akiko-pusu** [comment]
@ChrisR48 
Thanks for your additional information, and I'm sorry I couldn't be much of a help...

> May there be a permission issue or something like this.

As you mentioned above, I suppose someone who has manage template permission removed 
inadvertently.
So I'm going to add alert message / popup dialog just before template removed.
Because some templates may be used not only target project but also inherited projects, and if the templates are removed, inherited projects will have some impact.

How about?
Also, any suggestion, requests will be welcomed!

**Comment by ChrisR48** [comment]
The alert message sounds like a good point. Also a suggestion would be, that templates are not removed from the database but just flagged "deleted". With this an administrator could reactive a once deleted template.
As templates are not that large this should not be a storage issue.

**Comment by akiko-pusu** [comment]
> Also a suggestion would be, that templates are not removed from the database but just flagged "deleted”.

I’ve already implemented related feature, “Enabled/Disabled” templates, so I’d like users to use this feature like soft delete.  With adjusting UI and messages, I think this may be used as deleted flag.
Thanks again for your suggestion!

**Comment by ChrisR48** [comment]
Hi thats good. 

I will close this issue than.

Best regards

Christian
