### ISSUE TITLE
Wrong column label in "Preview Template Contents" modal dialog

### ISSUE THREAD

**Issue by tofi86** [akiko-pusu/redmine_issue_templates#154]
In the "Preview Template Contents" modal dialog there is the wrong label for the first column:

![grafik](https://user-images.githubusercontent.com/365118/29121963-002d51f0-7d11-11e7-9496-e3b93848129b.png)

The issue template's **name** is `Test`, not the issue title:

![grafik](https://user-images.githubusercontent.com/365118/29122046-2fbe9122-7d11-11e7-892b-c3e9ff4ae0b4.png)

So you should either add a new column in front of the first one and name it "template name" or you should not insert the "template name" in the "issue title" column.

**Comment by akiko-pusu** [comment]
@tofi86 Thanks for your reporting issue.
I’ve just fixed and merged into master. Also, I’m going to review and merge your pull request soon.
