### ISSUE TITLE
[Bug] Template list disappeared when change tracker

### ISSUE THREAD

**Issue by cuoilennaocacban** [akiko-pusu/redmine_issue_templates#167]
When I change tracker type, template list disappeared

**Comment by akiko-pusu** [comment]
Hi, @cuoilennaocacban 
If selected tracker has not any templates,  template list (pulldown for template) is not shown. 
The behavior is by design.

**Comment by cuoilennaocacban** [comment]
Sorry my bad. I should have test my code more carefully

**Comment by akiko-pusu** [comment]
@cuoilennaocacban 
No problem. And thank you so much for your trying my plugin.
Of course, if above is an obvious bug, I’m going to fix as soon as possible.
Please feel free to send feedbaks, questions, requests.
