### ISSUE TITLE
デフォルトを指定していた際の本文（説明）上書き

### ISSUE THREAD

**Issue by hachibay** [akiko-pusu/redmine_issue_templates#168]
デフォルトで設定したテンプレートがあるときに、テンプレートを選択すると、説明文に追記されてしまいます。もちろん「タイトルと詳細をクリア」を押して適用すれば大丈夫なんですが、できれば上書き（一度valをリセットしてからappend）のほうが効率としては高い気がしました。
設定（既存のデフォルト、有効のboolean設定と同列で上書きオプション）としての提供でもかまいませんが検討をお願いいたします。

**Comment by akiko-pusu** [comment]
こんにちは。
ご利用とissueの登録、ありがとうございます！

バージョン0.0.7で、テンプレートを切り替えてテンプレートのデータを読み込む際、上書きするか追加(append) するかを切り替えできる機能をつけております。

https://www.redmine.org/plugins/redmine_issue_templates

v0.0,7 - Add option to change append or replace with template.

こちらではご要望に不足する形でしょうか？
（上書きするか追加するかの設定はプロジェクト単位で切り替えになります。デフォルトは追加の動作です）
ご返答いただければと思います。

**Comment by hachibay** [comment]
早速のご回答ありがとうございます。
プロジェクト単位での設定とのことで設定箇所を見逃しておりました。
十分に要望を満たしております。ありがとうございます。

**Comment by akiko-pusu** [comment]
@hachibay ご確認ありがとうございました！
ドキュメントがちょっと追いついておらず、ご迷惑おかけしてしまいました。

その上で、ご要望などございましたら、お気軽にリクエストを出していただければ幸いです！
現場を離れてしまっているので、実際に使われている皆さんのお声を頂けると幸いです。

どうぞよろしくお願いいたします。（返信不要です！）
