### ISSUE TITLE
Translation: orphaned templates from tracker

### ISSUE THREAD

**Issue by jwalkerbg** [akiko-pusu/redmine_issue_templates#170]
Hello,

I am creating Bulgarian translation of the plugin. Please explain me what is the meaning of "orphaned templates from tracker".

Regards

**Comment by akiko-pusu** [comment]
Hi,  @jwalkerbg 
Thanks for your trying my plugin and reporting question.

Message "orphaned templates from tracker” was added on this commit, d2b8557. (#139)

"orphaned templates from tracker" is a template that is no longer associated with any other tracker.
Basically, every issue templates are associated with one tracker. 
If the tracker was removed, templates related to to removed tracker were not displayed on template list (template index) page. Also, user could not accessed to these templates and re-associated them with some other trackers.

After version 0.1.7, enabled to show such a templates as "orphaned template” and to edit these templates.

![orphaned_templates](https://user-images.githubusercontent.com/122621/34636163-0ae3b69a-f2df-11e7-8b44-841f259902d1.JPG)

Did you understand my explanation?
Of course, please suggest any suitable statement, i18n message if you have.

**Comment by jwalkerbg** [comment]
Hi, @akiko-pusu 
Thanks for your answer. I understood the meaning of "orphaned template".
I also think that "orphaned" is quite suitable for the case : the template had a tracker, then the tracker has gone away and the template is sitting alone without any tracker now.

Thank you, have a nice day.

**Comment by akiko-pusu** [comment]
It seems this was closed with PR #171
