### ISSUE TITLE
Issue Templates pluginでのソートが動作しない

### ISSUE THREAD

**Issue by tamaryo** [akiko-pusu/redmine_issue_templates#174]
Unofficial Redmine Cookingで上げた内容と同一です。

環境
Redmine  3.4.3
Ruby  2.4.2-p198
Rails  4.2.8
PostgreSQL  9.2.23
Issue Templates plugin  0.1.8

途中でトラッカーを増やして、テンプレートを分けるとpositionの値が離れてしまい、↑↓が動作しなくなることがあります。

通常ならば1から通番で振られていると思うのですが、5の次が12とか間が空いてしまっており、その間をアップダウンの矢印をクリックしてもpositionの数値が12を超えないため、移動しないようです。

我々が行った対策
SQLのpositionの値を再整理
1.RedmineサーバにSSHでログイン
2.PSQLにredmineのDBのユーザで入る
3.下記のクエリを実行する。(「 tracker_id = 」はトラッカーIDを指定する。)
これはトラッカー毎にタイトル名で昇順ソートし、その連番を位置情報として設定するという処理。
<pre>
update
 issue_templates a
set
 position = 
  (
   select
    pos
   from 
    (
     select
      id
      , row_number() over(order by title) as pos
     from
      issue_templates
     where
      tracker_id = 6
    ) b 
   where
    a.id = b.id
  )
where
 tracker_id = 6;
</pre>

**Comment by akiko-pusu** [comment]
@tamaryo さま、こんにちは。
Issueの報告ありがとうございます、助かります。

ソートの件ですが、お使いのRedmine3.4だとTrackerやStatusなどは確かDrag & Dropで移動できるようになっていましたよね。
Issue templateはこちらにまだ対応していないのですが、Redmine4向けに準備している環境では、Drag & Drop対応を取り込んでいます。
しばらくみなさんRedmine3.4系中心になるかと思うので、この点だけ対応できるかどうか試してみます。

また、Workaroundでのrake taskかrails consoleでのオペレーション方法も添えてみようと思います。

**Comment by tamaryo** [comment]
akiko-pusuさん

ご報告が遅れてしまい申し訳ございませんでした。

4系では改善されるということで承知致しました。

3.4では一部ドラッグアンドドロップで移動できるようになっているので、そうなってくれるとすごく助かります！

**Comment by y503unavailable** [comment]
いつも対応ありがとうございます。
質問と意見です。

positionの取扱い、、
表示順番に用いる相対的な上下関係（間隔不問）とするか、連続値を前提とするか。
どちらでしょうか？

後者かと思いますが、機能追加時に影響受け易い気がします。（ロバスト性）
勿論、作者の設計判断ですが。

workaroundについて

workaroundとしてのRailsConsole操作、
一般のadminに要求するユーザレベルとしては高い気がします。
コンソール操作権限必要ですし。

自分が聞かれたら、workaroundとしては、設定画面の内容をコピペして再設定し、前のエントリを削除するよう伝えます。
数件なら大した作業にもなりませんから。

＞added this to the v0.1.7 milestone 
v0.1.8 リリース済

**Comment by akiko-pusu** [comment]
@y503unavailable さん
こちらわたしの側で修正対応します。

もちろパッチ提供いただくのも大歓迎ですし、本来はこちらのほうが助かります...
ベストエフォートなので、そこまですぐには着手できませんので、あとは静観いただけると幸いです。

**Comment by akiko-pusu** [comment]
v0.1.9のリリースいたしました。
Drag and DropはRedmine本体の機能を流用していますが、一応 簡単なE2Eテストをつけてみています。
マイグレーションなどの大きな変更は無いので、もし可能ならお試しいただけると幸いです。

また、本番データ・たくさんのテンプレートを利用している現場の事例は大変貴重ですので、お気づきの点があれば引き続きご指摘いただけると幸いです。

**Comment by y503unavailable** [comment]
v0.1.9にアップデートしましたが、気になる点がありました。
＃必要なら別チケット起こします。

複数トラッカー用のがある場合、二つ目のトラッカー用のテンプレートを移動しようとすると、一つ目のトラッカーに重なって、下記画面の場合はテンプレート二つくらいずれている様です。最終的には移動します。

![image](https://user-images.githubusercontent.com/19310089/38378696-74b37cd6-3939-11e8-880e-641274f34057.png)

あと、assetのCSS更新失敗（(なんか以前合ったような気がします）、こちらはyum updateで復旧

**Comment by akiko-pusu** [comment]
こんにちは。どうもありがとうございます。
もし可能ならPull Request送っていただけると助かります！
assetのCSS更新失敗は、Redmineの側に揃えているかなと思うので、ちょっとご確認いただけますか？

**Comment by akiko-pusu** [comment]
@y503unavailable テスト用のデータも可能ならマスクした形でもいいので、SQLかCSVでご提供いただけると助かります。

**Comment by y503unavailable** [comment]
@akiko-pusu
テスト環境のvpsなので、直接見て頂いて構いませんが。。

**Comment by akiko-pusu** [comment]
ちょっと中に入る余裕はないので、ぜひダンプで。

**Comment by y503unavailable** [comment]
了解しました。
GlobalTemplateの設定画面だけなので、関連DBのSQL出します。

仕様確認
１．テンプレートの表示順序をD&Dするとき、移動対象のレコードは黄色反転表示としていますか？
　　黄色反転になる場合、白表示の場合があります。

２・移動操作開始時の表示位置は、元の場所の近くですよね？
　　自分の環境では、最初のトラッカーの場合は元の場所から表示されますが、二つ目以降のトラッカーでは上に数項目ずれて表示されます。

**Comment by tamaryo** [comment]
お忙しいところ新バージョンのリリースをして頂きありがとうございます！

**Comment by tamaryo** [comment]
上記の項目がずれる現象ですが、私の検証環境下では発生していないことをお伝えしておきます。

Redmine version                3.4.2.stable.16970
  Ruby version                   2.4.2-p198 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL

**Comment by y503unavailable** [comment]
0.1,9の項目がずれる件、Themeとの相性問題だったようです。
すみません。

闇鍋に入れているPurpleMine2を利用し、現象が発生していましたが、
他のThemeに変更すると、問題無く項目選択-移動できました。
(再度purplemine2に戻すと項目ずれ再発）
