### ISSUE TITLE
can´t open plugin configuration page due 404 error

### ISSUE THREAD

**Issue by carodrigues** [akiko-pusu/redmine_issue_templates#184]
After install "Redmine Issue Templates plugin", can´t open configuration due error:

404
A página que está a tentar aceder não existe ou foi removida. 
Voltar

I'm using redmine 3.4.2.2. 
Plugin was downloaded today.

**Comment by akiko-pusu** [comment]
Hi, @carodrigues 
Thanks for your trying my plugin!

Could you please tell me more about your environment information?

1. Plugin version (The latest version is 0.2.0)
2. Redmine version
3. Another plugin names (if you installed).
4. OS version and ruby version.

At first, please confirm that plugin’s directory name is “redmine_issue_templates” or not.

Plugin’s directory name should be the same with the one written in “init.rb”
So this plugin must be located as “redmine_issue_templates” under plugins directory.

Here is an example:
```
redmine-3.4.4 $ tree -L 1 plugins/
plugins/
├── README
├── redmine_issue_stamps
└── redmine_issue_templates # please check!

2 directories, 1 file
```

In addition to this, please follow the direction to install this plugin written in README.

> Copy the plugin directory into the $REDMINE_ROOT/plugins directory. 
> Please note that plugin's  folder name should be "redmine_issue_templates". 
> If changed, some migration task will be failed.
>
> Do migration task.
> e.g. rake redmine:plugins:migrate RAILS_ENV=production
>
> (Re)Start Redmine.

After confirming above, if you still have problems, please let me know error message in production.log.

**Comment by carodrigues** [comment]
Hi,

Redmine version is "3.4.2-2", please check the attached image with all
redmein info:

The plugin dir name was "redmine_issue_templates-master", i changed to "
redmine_issue_templates".
It seems this was the source problem. After reinstalling, it is ok.

Regards,
Carlos

**Comment by akiko-pusu** [comment]
Hi, @carodrigues 
I’m glad to hear that, and I’m going to close this issue.
Please feel free to post issues or requests :)

**Comment by carodrigues** [comment]
Hi,

I just have a question more.
I can´t see, when adding a new issue, the "issue template.

I gived permitions for role:




templates aren´t global, they are applied to one project.






Do you have some ideia of what is missing?

Regards,
Carlos
