### ISSUE TITLE
can´t see, when adding a new issue, the "issue template. 

### ISSUE THREAD

**Issue by carodrigues** [akiko-pusu/redmine_issue_templates#185]
I can´t see, when adding a new issue, the "issue template. 

I gave permissions for role:
![unnamed](https://user-images.githubusercontent.com/11546961/41044400-1fd1d9e8-699e-11e8-9490-c090db6b0ef0.png)

![unnamed](https://user-images.githubusercontent.com/11546961/41044475-43bb2576-699e-11e8-8dd3-3d341453f57f.png)

Templates aren´t global, they are applied to one project. 

![unnamed](https://user-images.githubusercontent.com/11546961/41044494-4ad26bc6-699e-11e8-92d0-58da9a208852.png)

![unnamed](https://user-images.githubusercontent.com/11546961/41044505-4f70ccae-699e-11e8-87e4-a61893b796dc.png)

Do you have some ideia of what is missing? 

Regards,
Carlos

**Comment by akiko-pusu** [comment]
Template should be marked as “Enabled".  (Maybe, “Habilitado” )
If not checked, the template is hidden and marked as draft.

**Comment by akiko-pusu** [comment]
@carodrigues 
Can I close this issue?

And I'm sorry I could not figure out that you wrote: 

> Your plugin template only refers the checklist (add one by one) but doesn´t
> refer the "add from template" checklist. Do you know why?

> Your template with checklist:

Do you have any trouble?
If so, I'll remove this featue to integrate Cheklist plugin.

**Comment by carodrigues** [comment]
Hi,

I only have an issue.

As i told, your pluging doesn´t have all functionalities of "CheckList
plugin". Do you think  it possible to integrate all functionalities of "
CheckList"?

"CheckList plugin belongs to RedmineUp.


Regards,
Carlos

**Comment by akiko-pusu** [comment]
> your pluging doesn´t have all functionalities of "CheckList
plugin". 

Trial feature was implemented against the free version of "CheckList plugin".  Af course, free version of "CheckList plugin" has limited feature.

And If this causes user to confuse, I'm going to remove this integration for maintenance reason.
