### ISSUE TITLE
Issue model desapear after changing the issue type

### ISSUE THREAD

**Issue by carodrigues** [akiko-pusu/redmine_issue_templates#187]
I have two issue templates configured for a project. 
The first template is associated to issues type = group and the second to issues type = bug.

When adding a new issue, by default type is group, the template issue is shown. 
Now, i change the type to bug. I was expecting to see the issue template but it is shown. 
If i change back to group, the issue template isn´t also shown. 

Issue model configuration for project "bug":

![image](https://user-images.githubusercontent.com/11546961/41149218-f1dfc098-6b02-11e8-8907-1a31148b57a3.png)

Adding new issue for project model, by default the issue type is "group":

![image](https://user-images.githubusercontent.com/11546961/41149317-2e767f92-6b03-11e8-96f5-e54d2d661286.png)

As you can see the issue template is show.
Now i change to type "bug":

![image](https://user-images.githubusercontent.com/11546961/41149381-4c99c006-6b03-11e8-8560-0b88eddfc835.png)
As you can see, the issue template isn´t shown. 

![image](https://user-images.githubusercontent.com/11546961/41149422-6c458746-6b03-11e8-9bb6-41a5c5c40baa.png)

Changing back to group, the issue template isn´t shown.

**Comment by akiko-pusu** [comment]
I can’t support you without any environmental information, as I already requested twice at #184 and #185, #186.
Also now I don’t have much time to spare for you.
I wonder you did not run plugin migration task yet. Please read README and Redmine’s official site.
