### ISSUE TITLE
bypass confirmation screen on new issue

### ISSUE THREAD

**Issue by undigo** [akiko-pusu/redmine_issue_templates#190]
## Summary
bypass confirmation when user create an new issue with default template

## Description
When user create an new issue with template, is it possible to force applying the default template with not see confirmation screen for yes / non mandatory button to apply the subject / description field  modification ?

## Environment
Redmine version                3.4.3.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.7
  Git                            2.14.1
  Filesystem                     
Redmine plugins:
  additionals                    2.0.11
  clipboard_image_paste          1.12
  computed_custom_field          1.0.6
  disable_activity               0.0.1
  event_notifications            2.4.1
  redmine_banner                 0.1.2
  redmine_ckeditor               1.1.5
  redmine_custom_css             0.1.7
  redmine_custom_reports         0.1.5
  redmine_default_custom_query   1.3.0
  redmine_drafts                 0.2.0
  redmine_email_notification_content_filter 0.0.2
  redmine_issue_subject_generator 0.0.1
  redmine_issue_templates        0.1.8
  redmine_knowledgebase          3.3.1
  redmine_landing_page           0.1.1
  redmine_logs                   0.1.1
  redmine_privacy_terms          1.0.0
  redmine_tkgmap                 0.1
  redmine_user_specific_theme    1.2.0
  redmine_workflow_enhancements  0.5.0
  redmine_workflow_hidden_fields 0.5.0These informations are greatly helpful to support quickly.
You can get these informations from Redmine's information page.
(E.g. http://example.com/admin/info)

The real need is to bypass subject field on new issue with anything value because user do not use this field, but I do not find plugin or workaround about this use case.

**Comment by akiko-pusu** [comment]
Hi @undigo 
Thank you for your trying and using my plugin.

> it possible to force applying the default template with not see confirmation screen for yes / non mandatory button to apply the subject / description field modification ?

Default template is applied without any confirmation dialog, but in case overwrite / replace option is activated, confirmation dialog will be shown. This is because to prevent the data that user filled out from overwriting and  losing by default template without confirmation.

You can change the behavior from project setting tab, lie this:

![replace option](https://user-images.githubusercontent.com/122621/41494724-8d7e3a8e-7152-11e8-84c6-523a400ac38a.png)

Does changing above setting meet your request?
Do you hope skip confirmation dialog message if default template overwrites all the data that user took   a long time to describe?

**Comment by akiko-pusu** [comment]
@undigo, How is the situation?

**Comment by undigo** [comment]
The activation of this option "Replace subject & description" is good to the usecase of user who create issue with only Subject field prefilled (description field is not use).
To ensure to not crush the subject field (/ description field) when user edit issue without confirmation dialog box, perhaps a second option only on new issue would be necessary ? like : "Replace Subject and description on new issue only"
The goal is to facilitate step creation for end user (not geek), so your module prefilled mandatory Redmine subject field is perfect for that !  The another custom fields are prefilled with default value on creation step.
no conflit with another plugin.
Thank you
Regards,

**Comment by akiko-pusu** [comment]
@undigo Thanks for your feedback.
I personally confirmation dialog for overwriting is a little annoying. 
So, I’ve add the feature that each user can hide this dialog with using browser cookie.
This feature was included in v0.2.1, so please confirm if you could.
