### ISSUE TITLE
Template checkboxes only display in some cases

### ISSUE THREAD

**Issue by Sidnioulz** [akiko-pusu/redmine_issue_templates#191]
## Summary of problem

When creating an issue from my project, and selecting a template with a checkbox, everything works well and the issue checkbox is filled in.

However, when creating an issue from the `my.redmine.path/issues/new` URL, selecting the project with the template, then selecting the template, the checkbox part of the template is not applied.

## Environment

Setting `Replace subject and description Help for this field.` to false or true does not affect the bug behaviour.

Network requests between both outlined scenarios appear identical.

> Environment:
>   Redmine version                3.4.6.stable
>   Ruby version                   2.3.7-p456 (2018-03-28) [x86_64-linux-gnu]
>   Rails version                  4.2.8
>   Environment                    production
>   Database adapter               PostgreSQL
> SCM:
>   Subversion                     1.8.8
>   Darcs                          2.8.4
>   Mercurial                      2.8.2
>   Cvs                            1.12.13
>   Bazaar                         2.7.0
>   Git                            2.17.1
>   Filesystem                     
> Redmine plugins:
>   redmine_checklists             3.1.5
>   redmine_custom_css             0.1.6
>   redmine_image_clipboard_paste  3.3.0
>   redmine_issue_templates        0.1.7
>   redmine_omniauth_google        0.0.1
>   sidebar_hide                   0.0.8
> 
> - Redmine version
> - Installed plugins
> - Ruby version
> - OS Platform
> - Database (MariaDB, MySQL, PostgreSQL) and its version
> - Rails Env

## Visual Proof / Screenshot

Sadly I do not have access to a log at the moment.

## Expected Results

The checklist should be filled in based on the template regardless of how the ticket is created.

## Actual Results

_(as described in summary)_

**Comment by akiko-pusu** [comment]
Hi, @Sidnioulz 
Thanks for using my plugin and reporting this issue.
Also, I really appreciate that you filled in some informations related to your environment.
These are quite helpful for me 😃 

> my.redmine.path/issues/new URL, selecting the project with the template, then selecting the template, the checkbox part of the template is not applied.

OK, I could understand the situation. 
Checklist integration option is related to project setting,  so this is becaiuse checklist option may not be loaded correctly in case you try to create issue without selecting project first.

> The checklist should be filled in based on the template regardless of how the ticket is created.

Do you think this defect is serious against your works?
Of course I’m going to estimate is it possible to fix it and how to fix it, but I need some time to do so.
Please wait for a while and give me some time.

**Comment by Sidnioulz** [comment]
Hi!

Yes, it is important to me because our organisation uses templates to help our non-IT users test applications before a release, for a variety of use cases. Templates describe test scenarios in the form of a checkbox list.

The end-users who test at the end of the release cycle are not too understanding of Redmine. When they start a test by creating an issue, they should be able to do so regardless of the URL used, especially since we use the generic /issues/new URL in our documentation and emails and some users test multiple projects.

So, whilst I can accomodate with the bug myself, it generates support requests from less technically-versed employees.

Maybe if you need to pull project info based on which project is selected, it would be easier to pull all checkbox settings for all projects on page load, or even to force checklists to be enabled across all projects for your plugin to work?

**Comment by akiko-pusu** [comment]
@Sidnioulz 
I'm sorry I could not reply to this issue so long time.
Now I support Redmine 4.x and the latest Issue Template plugin is v0.3.5.

I think this problem will be fixed if you update the Redmine and plugin.
So I'm going to close this issue.
