### ISSUE TITLE
The "issue body" is entered several times

### ISSUE THREAD

**Issue by psammer2** [akiko-pusu/redmine_issue_templates#194]
## Summary
If you change the "Assignee", the template's "issue body" is entered several times.

## Description
I created an issue template with these options:
![grafik](https://user-images.githubusercontent.com/42963533/45024045-62f9df00-b038-11e8-95a5-7b15d00b8d52.png)
![grafik](https://user-images.githubusercontent.com/42963533/45024931-668e6580-b03a-11e8-9eeb-7dcc1b9b2e48.png)

If I create a new task, enter some text in the "issue body" and change the "Assignee", the template's "issue body" will be added again to the entered text:
![grafik](https://user-images.githubusercontent.com/42963533/45025003-98073100-b03a-11e8-8010-d5fe5af5b00a.png)

## Environment
- Redmine version: "Easy Redmine 2016" https://www.easyredmine.com
- Installed plugins: "Basic Project Management", "Resource Management", "Finance Management", "Customer Management", "Advanced Project Management", "Easy Baseline", "Easy Buttons", "Easy checklist", "Easy Gantt", "Redmine Issue Templates"
- Ruby version: don't know, must ask.
- OS Platform: Linux, distribution: don't know, must ask.
- Database (MariaDB, MySQL, PostgreSQL) and its version: don't know, must ask.
- Rails Env: don't know, must ask.

## Visual Proof / Screenshot
see above.

## Expected Results
The "issue body" of the template should not be added several times.

## Actual Results
See above.

## Workaround
Annoying: must delete the added text

**Comment by mbrenguier** [comment]
Hi @akiko-pusu,

First of all, thanks for your awesome work. Same problem here each time I try to change tracker (it's kind similar of issue posted by @psammer2). 

Short example : 
My issue template for Bug is `hello, it's a bug`. (activated and set by default)
My issue template for Evolution is `hello, it's an evo`. (activated and set by default)

I want to create an Evolution, Bug is the default tracker in our projects. So, everytime a ticket is created, Bug is set as tracker and `hello, it's a bug` is set as issue body. I change my tracker for Evolution but my old pattern is always here, result : 

```txt
hello, it's a bug

hello, it's an evo
```

This, is very annoying for long patterns, it's added below the other one and most ppl don't see it or have to remove the old text manually.

Is it intended ? Is it not possible to clear automatically the old pattern ?

Big thanks for your help 👍

**Comment by akiko-pusu** [comment]
Sorry I have not still handle this issue yet.
But I do hope to make this plugin more user friendly, please wait for a while.

**Comment by akiko-pusu** [comment]
@psammer2 
Sorry for my delayed reply.
ButI could not reproduce this defect yet. 
Normally, template is not appended when assignee is changed.
In addition to this, I could not look into the causes for this problem because I’m not a user of Easy Redmine, which  may be customized from pure Redmine.
Also, since plugins listed above are private (not free) plugins that I can’t get these source code.

**Comment by akiko-pusu** [comment]
Please re-open if you still have any troubles.
