### ISSUE TITLE
Checklist from redmine_checklists is partially integrated into Template

### ISSUE THREAD

**Issue by gessel** [akiko-pusu/redmine_issue_templates#195]
This is a template to report bug related to redmine issue templates plugin.
You can fill in any format, free style in case report features or questions.

## Summary

With redmine_checklists (https://www.redmineup.com/pages/plugins/checklists) installed it is possible to create a new template that includes a checklist, but it doesn't seem to persist through a status change or saving a new task.

## Description

When creating a new template it is possible to create a checklist.  This appears when you select (or default to) the template in creating a new issue as expected.  But if you change the status of the issue from "new" (or default) to something else ("in progress") only 5 checklist items remain, the rest disappear.   If you create a new ticket without changing the status and save it, again, only 5 of the checklist items remain and the rest disappear.

## Environment

These informations are greatly helpful to support quickly.
You can get these informations from Redmine's information page.
(E.g. http://example.com/admin/info)

Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.4.4-p296 (2018-03-28) [amd64-freebsd10]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               Mysql2
SCM:
  Filesystem                     
Redmine plugins:
  periodictask                   3.3.0
  redmine_checklists             3.1.11
  redmine_custom_reports         0.1.5
  redmine_dmsf                   1.6.1
  redmine_email_images           0.1.1
  redmine_highlightjs            1.0.3
  redmine_image_clipboard_paste  3.3.0
  redmine_issue_templates        0.2.0
  redmine_sortable_table         0.99.1
  redmine_tweaks                 1.0.2

## Visual Proof / Screenshot

When reporting an application error, post the error stack trace that 
you should find in the **log file** (eg. log/production.log). 

Screen shot would be also helpful.

## Expected Results

Full checklist as defined in template persists in the ticket

## Actual Results

partial checklist as defined persists in the ticket.

## Workaround

I haven't found one.

**Comment by akiko-pusu** [comment]
Could you please give me some screenshot?
And let me confirm if you use free version of checklist plugin or paid version.

**Comment by gessel** [comment]
Hey, sorry for the delay - I thought I'd added some screen shots, but I don't see them here.  

It is the free version of the checklist plugin.

uploads seem to be failing (Something went really wrong, and we can't process that file.  Try again.)

Basically there are 17 items specified in the checklist in the template, which appear properly when a new issue is created and the template is selected, but when the issue is saved, only 5 checklist items are in the ticket.  The rest are just not there.

The template function is great for the text template, that works perfectly.

**Comment by akiko-pusu** [comment]
> only 5 checklist items are in the ticket
Thanks for above information.
I’m not sure if this is the restrict of Checklist plugin or not.
Can you create more than 5 checklists at the same time without template plugin?

**Comment by gessel** [comment]
Weirdly, it seems to work as expected with Chrome, but not Firefox.  I switched to the paid version of checklists and had the same problem with that version's templates with Firefox, so I don't think the problem is on your side.  With Chrome both the template plugin's version of checklist templates and the checklist (paid) version work as expected.

**Comment by akiko-pusu** [comment]
Thanks for above info! This is a useful clue for me to support :)
I'll try to confirm with Firefox later.
