### ISSUE TITLE
can't show issue templates when editing an issue

### ISSUE THREAD

**Issue by msl12** [akiko-pusu/redmine_issue_templates#196]
**Hi**,

We are using this plugin in our **Redmine** 3.4.6. It seems nice!

But we found that when editing an existing issue, it didn't show the issue templates.

Is this a feature that hasn't been accomplished yet?

**Comment by akiko-pusu** [comment]
@msl12 Thanks for your using my plugin and feedback.
I’m sorry this issue template is applied only when create new issue.

> editing an existing issue

Do you want template applied to issue’s body or issues reply (comment) ?

**Comment by msl12** [comment]
I see.

Maybe applying templates to issue comment is better.

Thanks a lot!

**Comment by akiko-pusu** [comment]
@msl12 Thanks for your feedback.
I'm going to implement this feature at #172 
So this question closed.

**Comment by akiko-pusu** [comment]
Sorry, re-open.
There are 2 requirements:

1. Apply template to issue description.
2. Apply template to note. (Example: When agent reply with template message.)

**Comment by akiko-pusu** [comment]
I've just released v0.3.1.
Sorry this version supports Redmine4.x only. 
I'm glad if you had trying this version :)
