### ISSUE TITLE
Cannot apply global template to project with MySQL group replication

### ISSUE THREAD

**Issue by yano0takashi** [akiko-pusu/redmine_issue_templates#197]
This is a template to report bug related to redmine issue templates plugin.
You can fill in any format, free style in case report features or questions.

## Summary
I could not apply global template to a project with MySQL group replication

## Description
I could not apply global template to a project with MySQL group replication.
Internal error occurs.
The reason is:
global_issue_templates_projects table has no primary key.
I add (project_id,global_issue_template_id) as a primary key and the problem is gone.

## Environment

These informations are greatly helpful to support quickly.
You can get these informations from Redmine's information page.
(E.g. http://example.com/admin/info)

- Redmine version
3.4.6
- Installed plugins
- Ruby version
2.3.1
- OS Platform
ubuntu 16.04
- Database (MariaDB, MySQL, PostgreSQL) and its version
MySQL 8.0.13
- Rails Env
4.2.8

## Visual Proof / Screenshot

When reporting an application error, post the error stack trace that 
you should find in the **log file** (eg. log/production.log). 

Screen shot would be also helpful.

## Workaround

Please let me know if you have any workaround.

**Comment by akiko-pusu** [comment]
@yano0takashi san, thanks for your reporting!
I could reproduce above situation. 

The error happened when save global issue template associated with project.
```
  SQL (3.4ms)  INSERT INTO `global_issue_templates_projects` (`global_issue_template_id`, `project_id`) VALUES (1, 1)
   (1.4ms)  ROLLBACK
Completed 500 Internal Server Error in 69ms (ActiveRecord: 25.2ms)

ActiveRecord::StatementInvalid (Mysql2::Error: The table does not comply with the requirements by an external plugin.: INSERT INTO `global_issue_templates_projects` (`global_issue_template_id`, `project_id`) VALUES (1, 1)):
  lib/redmine/safe_attributes.rb:84:in `safe_attributes='
  plugins/redmine_issue_templates/app/controllers/global_issue_templates_controller.rb:55:in `edit'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

And I could save it after adding primary key setting on  global_issue_templates_projects following your advise.
```
mysql> alter table  global_issue_templates_projects add primary key (project_id, global_issue_template_id);
Query OK, 0 rows affected (0.30 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

And I could save project and global issue template relation.

```
   (1.2ms)  BEGIN
  SQL (2.2ms)  INSERT INTO `global_issue_templates_projects` (`global_issue_template_id`, `project_id`) VALUES (1, 1)
   (14.0ms)  COMMIT
   (1.3ms)  BEGIN
```

I’ll try to make migration file to add primary key.  I’m sorry error may happen if you apply next release’s migration because  you have already primary key setting.

**Comment by akiko-pusu** [comment]
Hi, I’ve committed new migration to add unique index on global_issue_templates_projects.
(commit: 7b88170)

Though this is not a primary key, but I could confirm the problem fixed.
I’m going to release as new version and merge into master branch.

I think migration will be executed correctly even if you have already added a primary key.

DDL is following of my test env with MySQL group replication.

```
/* global_issue_templates_projects */
CREATE TABLE `global_issue_templates_projects` (
  `project_id` int(11) NOT NULL,
  `global_issue_template_id` int(11) NOT NULL,
  PRIMARY KEY (`project_id`,`global_issue_template_id`),   --- PK that you added
  UNIQUE KEY `projects_global_issue_templates` (`project_id`,`global_issue_template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```

And if you drop Primary key with ``ALTER TABLE global_issue_templates_projects  DROP PRIMARY KEY;`` statement,  this problem may not be happened if additional unique key constraint exists.

**Comment by yano0takashi** [comment]
I have confirmed that the problem is fixed.
I installed the redmine issue template at the releases.

**Comment by akiko-pusu** [comment]
ありがとうございます！
