### ISSUE TITLE
Internal Server Error when used with checklists plugin and redmine 4.0.1

### ISSUE THREAD

**Issue by SystemKeeper** [akiko-pusu/redmine_issue_templates#217]
I've upgraded to Redmine 4.0.1 and I'm using redmine_issue_templates besides redmine_checklists. After the update and using the latest version of both plugins I was unable to open project settings:
```
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>""}
  Current user: (id=8)
  Rendering projects/settings.html.erb within layouts/base
  Rendered projects/settings.html.erb within layouts/base (60.9ms)
Completed 500 Internal Server Error in 71ms (ActiveRecord: 2.3ms)

ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x0055ea476c26b8>:0x0055ea44c63688>
Did you mean?  project_settings_tabs_with_checklists):
    1: <h2><%=l(:label_settings)%></h2>
    2:
    3: <%= render_tabs project_settings_tabs %>
    4:
    5: <% html_title(l(:label_settings)) -%>

plugins/redmine_issue_templates/lib/issue_templates/projects_helper_patch.rb:6:in `project_settings_tabs'
plugins/redmine_checklists/lib/redmine_checklists/patches/projects_helper_patch.rb:37:in `project_settings_tabs_with_checklists'
plugins/redmine_issue_templates/lib/issue_templates/projects_helper_patch.rb:6:in `project_settings_tabs'
app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb__2052146827629815602_47232358820880'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

After reading about similar problems, I stumbled across this line:
https://github.com/akiko-pusu/redmine_issue_templates/blob/3a29bdd8078ba144e5dc27a0dc000b12a0a05dbf/lib/issue_templates/projects_helper_patch.rb#L18
after changing this to `ProjectsController.send :helper, IssueTemplates::ProjectsHelperPatch` it looks like everything is working fine again.

I'm by no means familiar with redmine development, so I'm not sure if this is really the way to solve this. Maybe someone can have a look and properly fix this.

**Comment by akiko-pusu** [comment]
@SystemKeeper
Thanks for your reporting this issue and your workaround.
To tell the truth, I don’t have Checklist plugin’s source code and I can’t reproduce and fix above now.

Let me confirm, checklist plugin you use supports Redmine4.x or not?
Could you tell me the version or resource of checklist plugin? (Free version? Paid one?)

It’s great help for me if you provide your environment information.
(E.g. please click https://github.com/akiko-pusu/redmine_issue_templates/issues/new and you can find the way to report your environment information.)

Thanks for your workaround again.
I think following change will also be effective.
 
```
# ProjectsHelper.prepend IssueTemplates::ProjectsHelperPatch
ProjectsController.helper(IssueTemplates::ProjectsHelperPatch)
```

**Comment by akiko-pusu** [comment]
Ready to fix.

**Comment by akiko-pusu** [comment]
Workaround was merged into master branch. Thanks!
