### ISSUE TITLE
Template visibility per role

### ISSUE THREAD

**Issue by vividtone** [akiko-pusu/redmine_issue_templates#229]
The note template feature that you have implemented in 0.3.1 is really nice for me. Thank you so much.

I think it will be even nicer if a template can be configured to be visible for specific roles like a visibility setting of a custom field or a custom query.

One of the Redmine instance in my company is used for customer support. The new note template feature is useful for helpdesk staffs but I don't want to show those templates for customers.

Not only for note templates I think the visibility setting is useful also for issue templates.

<img width="391" alt="image" src="https://user-images.githubusercontent.com/114863/54257080-88e0dd00-45a1-11e9-97ba-22dbd30bc89f.png">

**Comment by akiko-pusu** [comment]
> One of the Redmine instance in my company is used for customer support. The new note template feature is useful for helpdesk staffs but I don't want to show those templates for customers.

I had the situation like this with another ITS for customer support. 
So, I totally agree with above request and hope to implement this!

If you need this feature as soon as possible, of course, pull request is also highly welcomed.
Test code is not required. I can add the test / spec by miself :)

**Comment by akiko-pusu** [comment]
@vividtone Hi, I'm tying to implement this feature at this PR: #267 
The rest of tasks are some views and tests.
Please comment if you have any interest!

**Comment by vividtone** [comment]
Oh, I didn't know at all that you were working on implementing the feature. Thank you.

Yes, I really want this feature. Please let me know if there is something I can help you.

**Comment by akiko-pusu** [comment]
As a prototype, implemented a feature to handle note template’s visibility per role on #267 
You can try with ``template-visibility-per-role`` branch.
Feedback highly appreciated.

**Comment by vividtone** [comment]
It is a great feature! Thank you so much!!!!!
I have just begun testing the feature.

**Comment by akiko-pusu** [comment]
Hi, I close this issue.
v0.3.4 is a prototype version.
To implement this feature, I created an intermediate table. (NoteVisibleRoles)


If you think there is no problem with this implementation, I'm going to apply the same way to Issue Template.
So, please feel any comment / request / suggest in advance.
Because now I don’t manage and operate Redmine except hobby use.
I am worried if this implementation is appropriate or not for large-scale operations or performance.
