### ISSUE TITLE
Default values for standard issue fields

### ISSUE THREAD

**Issue by nosmicek** [akiko-pusu/redmine_issue_templates#241]
## Summary
Add feature to preselect standard values for new issues per template.
Not an issue actually, i woul classify this as a feature request.

## Description
We recently start to use your template plugin company wide and immediately needed to preselect some values at issue creation time, such as "assigne", "priority", "due date" and value of custom field (select box with users). 

On one project we use several templates, each of them have default issue solver, priority and due date, with one custom field. For example template "Close offer" should be assigned to one preselected man (role possibly) in sales department, with priority urgent and due date today, overview (custom field) preselected as head of sales dept (possibly user or role). Other template "pair offer with business lead" is assigned to a man from support, with priority normal, due date today + 1 day, overview (custom field) preselected as head of support dept. etc. you get the idea.
The idea is, that we would like to set those values preferrably in template, now we need people to always selected them on issue create.

## Environment

Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL 9.6.11
SCM:
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  issuecloser                    0.0.1
  issuecloser2                   0.0.1
  redmine_checklists             3.1.11
  redmine_dmsf                   1.6.1
  redmine_issue_templates        0.2.1
- OS Platform: Linux/Debian

## Workaround

Looked at many other plugins but cannot find any solution to this. We can set default assigne per project, but this would set assignee of all issuess in project regardless of template.

There seems to exist some plugins that deals with default values for custom fields, but those cant preselect assignee or priority etc.

**Comment by akiko-pusu** [comment]
Hi, I've just merged above PR into my develop branch.
Since this is an experimental feature, please be careful if you hope to try it.
Migration is required and some browsers may not work fine.

Hope this would be any help.
And if you still have interests in this feature, feedback would be highly appreciated!

**Comment by akiko-pusu** [comment]
merged into master branch. please re-open or report new issue.

**Comment by akiko-pusu** [comment]
@nosmicek 
Hi, I've released v1.0.0 to support custom fields and builtin-fields.
Since this is an experimental feature, please be careful if you hope to try it.

Please see https://github.com/akiko-pusu/redmine_issue_templates/releases/tag/1.0.0
I'm looking forward to your feedback.
