### ISSUE TITLE
Adding issue templates with checklists occurs internal error

### ISSUE THREAD

**Issue by maaru** [akiko-pusu/redmine_issue_templates#243]
## Summary
I got an internal error when adding issue template with checklist items.
There is no error when adding issue template without checklist items.
Both global and project template has same problem.

## Description
Adding issue template with checklist items occurs internal error.
I think `IssueTemplate.new(template_params)` does not support `checklists` params.

Editing issue template with adding checklist items does not have problem.

## Environment
```
Environment:
  Redmine version                4.0.3.stable
  Ruby version                   2.4.5-p335 (2018-10-18) [x86_64-linux-gnu]
  Rails version                  5.2.2.1
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.3
  Mercurial                      3.7.3
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.21.0
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.9
  redmine_checklists             3.1.15
  redmine_issue_templates        0.3.1
  redmine_people                 1.4.0
  view_customize                 2.1.0
```

## Visual Proof / Screenshot
```
Started POST "/projects/forty/issue_templates" for 127.0.0.1 at 2019-05-13 12:28:31 +0900
Processing by IssueTemplatesController#create as HTML
Parameters: {"utf8"=>"✓", "authenticity_token"=>"***", "issue_template"=>{"title"=>"Checklist test", "tracker_id"=>"1", "issue_title"=>"Test", "description"=>"", "checklists"=>["テスト"], "note"=>"", "is_default"=>"0", "enabled"=>"0", "enabled_sharing"=>"0"}, "commit"=>"Create", "project_id"=>"project"}
Current user: xxxxx (id=5)
Completed 500 Internal Server Error in 11ms (ActiveRecord: 2.7ms)

ActiveModel::UnknownAttributeError (unknown attribute 'checklists' for IssueTemplate.):

plugins/redmine_issue_templates/app/controllers/issue_templates_controller.rb:51:in `create'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

## Workaround
Adding new issue template without checklists, after editing with checklist.

**Comment by akiko-pusu** [comment]
Hi, @maaru san
Thanks for your reporting issue, this is great helpful information!
I'm sorry I could not find this problem and replied so late.

I've just merged the workaround into develop branch. 
Please see: https://github.com/akiko-pusu/redmine_issue_templates/pull/247

If no problem, I'm going to update master branch and release  a bug-fix version.

**Comment by maaru** [comment]
Hi, @akiko-pusu san
Thank you for your reply.
I tried to test the code of develop branch, but there is no problem!
I appreciate your swift response. 😄

**Comment by maaru** [comment]
@akiko-pusu さん
お忙しい中、迅速なご対応ありがとうございました！
英語はあまり得意では無いので、もしミスなどあればご容赦ください... 😭

**Comment by akiko-pusu** [comment]
@maaru san
Thanks for reply.
To tell the truth, when updating template, cheklists might not be saved correctly.
I'll confirm and add another code soon. If there is something wrong, I 'll release once again 🙏

**Comment by maaru** [comment]
@akiko-pusu san
Oh... I'm sorry. My test was not enough.
Checklist items were certainly not updated on my local environment.
I look forward to next release. (please don't feel pressure because I have workaround and not serious problem. ☺️ )

**Comment by akiko-pusu** [comment]
@maaru 
ありがとうございます。修正のPR用意しました。本体部分のモデルに少し加えるだけの修正で済むと思います。
テストの分長いですが、'checklist_json' を追加のみで大丈夫だと思います。
```
  safe_attributes 'title', 'description', 'tracker_id', 'note', 'enabled', 'issue_title', 'is_default',
-	                  'enabled_sharing', 'visible_children', 'position'
+	                  'enabled_sharing', 'visible_children', 'position', 'checklist_json'
```

I'm going to apply this PR for updating defects.
https://github.com/akiko-pusu/redmine_issue_templates/pull/249

**Comment by maaru** [comment]
@akiko-pusu san
PR作成とmergeありがとうございます。
`develop` branchをcheckoutしてlocalのredmineでテストしたところ、プロジェクトのissue_templateでは新規追加・更新共に問題なく動作しました。

しかし、管理メニューのグローバル チケットテンプレートでは、新規追加は問題ありませんが更新が反映されない問題がまだ残っているようです。
もし問題が再現されない場合はコメントいただけると助かります！

**Comment by maaru** [comment]
https://github.com/akiko-pusu/redmine_issue_templates/blob/develop/app/models/global_issue_template.rb#L9-L18

global_issue_templateのモデルのsafe_attirbutesにも `checklist_json`が必要そうですね

**Comment by akiko-pusu** [comment]
ありがとうございます！

**Comment by akiko-pusu** [comment]
修正分をマージして、v0.3.3に反映させました。
ご協力ありがとうございます！

https://github.com/akiko-pusu/redmine_issue_templates/pull/255

**Comment by maaru** [comment]
v0.3.3にて問題なく動作しました 👍 
ご対応ありがとうございました！
