### ISSUE TITLE
The last one checklist can not be deleted.

### ISSUE THREAD

**Issue by ryouma-nagare** [akiko-pusu/redmine_issue_templates#256]
## Summary
The last one checklist can not be deleted.

## Description
If there is only one checklist, deletion will not be reflected after saving.
I have more than one checklist, I can delete them in any order.

I am using redmine_checklists-3_1_16-light.zip.

## Environment
- Redmine version
  - 4.0.3.stable.18211
- Installed plugins
  - group_watchers                 0.0.1
  - redmine_absolute_dates         0.0.4
  - redmine_banner                 0.2.0
  - redmine_checklists             3.1.16
  - redmine_code_review            1.0.0
  - redmine_issue_templates        0.3.3
  - redmine_jstoolbar_ext          0.2.1
  - redmine_jstoolbar_ext_buttons  0.2.1
  - redmine_jstoolbar_ext_coderay  0.2.0
  - redmine_vividtone_my_page_blocks 2017/07/05
  - redmine_wiki_extensions        0.9.0
  - redmine_wiki_index_tree_view   0.0.1
  - redmine_wiki_lists             0.0.9
  - redmine_wiki_page_tree         0.0.2
  - redmine_work_time              0.4.0
  - redmine_xls_export             0.2.1.t11
  - view_customize                 2.2.0
- Ruby version
  - 2.4.4-p296
- OS Platform
  - CentOS Linux release 7.6.1810 (Core)
- Database (MariaDB, MySQL, PostgreSQL) and its version
  - PostgreSQL11/MariaDB 10.1.6
- Rails Env
  - 5.2.3

## Visual Proof / Screenshot

![image](https://user-images.githubusercontent.com/12542118/58684716-1fa88300-83b4-11e9-91a8-c661cdbac742.png)

no errors in production.log

**Comment by akiko-pusu** [comment]
Thanks for your reporting!
Maybe this commit will be effective.
https://github.com/akiko-pusu/redmine_issue_templates/pull/258/commits/b159597749d815d78631d0df3cc2e201e089ba4b

I’m going to update plugin soon, but please try to apply above commit :)

**Comment by ryouma-nagare** [comment]
I confirmed that this problem was solved on 
- redmine_issue_templates 0.3.4 + Redmine 4.0.4.devel.18314
- redmine_issue_templates 0.3.4 + Redmine 4.0.4.stable.18314

Thank you!
