### ISSUE TITLE
Issue template visible only in admin when i switch to an other user no template display

### ISSUE THREAD

**Issue by mos89** [akiko-pusu/redmine_issue_templates#257]
This is a template to report bug related to redmine issue templates plugin.
You can fill in any format, free style in case report features or questions.

## Summary
Issue template visible only in admin when i switch to an other no template display

## Description
Issue template visible only in admin when i switch to an other no template display

## Environment

These informations are greatly helpful to support quickly.
You can get these informations from Redmine's information page.
(E.g. http://example.com/admin/info)

- Redmine version 4.0.3
- Installed plugins

Clipboard image pastePaste cropped image from clipboard as 

Redhopper pluginKanban boards for Redmine,
Redmine Issue Templates pluginPlugin 
Issue To-do Lists
Visual Comments ToolT

- Ruby version: ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]
- OS Platform windows server 2008 R2
- Database (MariaDB, MySQL, PostgreSQL) and its version MySQL
- Rails Env

## Visual Proof / Screenshot

When reporting an application error, post the error stack trace that 
you should find in the **log file** (eg. log/production.log). 

Screen shot would be also helpful.

## Workaround

Please let me know if you have any workaround.

**Comment by mos89** [comment]
you can delete it, it was a configuration problem from me

**Comment by akiko-pusu** [comment]
@mos89 
Thanks for your reporting issue. And I'm glad to hear that.
Sorry the installation document is not the same repository but other site.

https://www.r-labs.org/projects/issue-template/wiki/About_en

I'm going to move above document on this repository's wiki.
Please feel free to post if you have any requests, problems and so on.
