### ISSUE TITLE
The note_template can not be applied due to the hard coding of the URL if Redmine running in a subdirectory.

### ISSUE THREAD

**Issue by ishikawa999** [akiko-pusu/redmine_issue_templates#260]
## Summary

The note_template can not be applied if Redmine running in a subdirectory.

## Description

I run Redmine in a subdirectory.
Example:
  `https://my.domain/app1`
  `https://my.domain/app1/issues` (when accessing issues)

When applying note_template fails, the following error message is output in DevTools console.
```
POST https://my.domain/note_templates/load 404 (Not Found)
```
Expected: `POST https://my.domain/app1/note_templates/load`

I think that the cause is that the URL is hard-coded in https://github.com/akiko-pusu/redmine_issue_templates/blob/master/app/views/issue_templates/_note_form.html.erb#L98 .

## Environment

- Redmine version 4.0-stable

**Comment by akiko-pusu** [comment]
Thanks for this reporting and pull request!
I've just merged your PR into master because this is quite helpful.

**Comment by ishikawa999** [comment]
Thank you for your quick response.

**Comment by akiko-pusu** [comment]
It's my pleasure!
