### ISSUE TITLE
No dropdown menu to select templates when creating an issue

### ISSUE THREAD

**Issue by johnle** [akiko-pusu/redmine_issue_templates#264]
Hi there,

I hope you can help with this. I've enabled the plugin and set the permissions, but there's still no option to select a template when creating an issue.

Here's some additional info:
```
Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  redmine_issue_templates        0.2.1
```

Thanks!

**Comment by akiko-pusu** [comment]
Hi, @johnle, thanks for using my plugin!
Issue templates should be marked as "**enabled**" to use. 
Please confirm if each template is marked as "enabled" or not?
Also user who want to use (select) issue template when creating issue, "show templates" permission is required.

**Comment by johnle** [comment]
Hi @akiko-pusu 

Yes, here's what I've already done:
- Enabled the plugin in 'Modules'
- Enabled the template
- Set the permissions to 'Show Templates'

But there is still no option to select a template when creating an issue.

**Comment by akiko-pusu** [comment]
Let me confirm, did you create any templates?
If there is no template, pulldown does not appear.

**Comment by johnle** [comment]
Yes, I did create the templates as well.

**Comment by akiko-pusu** [comment]
@johnle 
How is the situation?
I need some more info to support this problem.

- Do you use any other plugins?
- Do you use Redmine under the sub-URI?
- Could you give me some log information when creating an issue?
- What browser do you use?
  - Does this problem happen when you use other browsers?
