### ISSUE TITLE
Issue body repeats after category is changed

### ISSUE THREAD

**Issue by julianmj** [akiko-pusu/redmine_issue_templates#269]
## Summary
Hi there, 
While registering a issue the body template is applied again when a category is chosen.  This only happens with redmine_ckeditor plugin is active.

redmine_ckeditor plugins adds CKEDITOR to Redmine.

## Environment

Environment:
  Redmine version                4.0.1.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  computed_custom_field          1.0.7
  redmine_ckeditor               1.2.1
  redmine_custom_reminder        0.6.3.b7100aa
  redmine_issue_templates        0.3.0
  redmine_issues_tree            0.0.13

## Visual Proof / Screenshot
Ckeditor-Configuration
![image](https://user-images.githubusercontent.com/31073809/62306235-1173f300-b447-11e9-8bb8-54eb00954db6.png)

Template
![image](https://user-images.githubusercontent.com/31073809/62306355-56982500-b447-11e9-9176-665a542921f4.png)

New issue
![image](https://user-images.githubusercontent.com/31073809/62306400-6dd71280-b447-11e9-8525-180d52975f0d.png)

When a category is chosen
![image](https://user-images.githubusercontent.com/31073809/62306446-85ae9680-b447-11e9-8560-a0a3cf024081.png)

![image](https://user-images.githubusercontent.com/31073809/62306672-e4741000-b447-11e9-9361-2cbad019de21.png)

After a category is chosen
![image](https://user-images.githubusercontent.com/31073809/62306496-9bbc5700-b447-11e9-854a-24e5646b4d6b.png)

This process happens every time the category is changed. 

## Workaround

Don't have a workaround

Thank you so much for your help. Your plugin is super useful !

**Comment by akiko-pusu** [comment]
@julianmj Hi, thanks for using my plugin and reporting this issue.
Let me confirm. 

- Only a default template content is loaded every time you change issue’s category, is this right?
- Have you been using this plugin from older version of Redmine? (Such as Redmine 3.x)
  - If so, has this problem been present since then?

**Comment by akiko-pusu** [comment]
Hi, I tried to reproduce this problem with plain Redmine / IssueTemplate / CKEDitor, but can’t reproduce it. (
If you can, please update template version to 0.3.4 (latest).

**Comment by julianmj** [comment]
Hi,

I updated both plugins, CKEditor 1.2.2 and IssueTemplate 0.3.5. Problem solved.

Thanks!
