### ISSUE TITLE
The template list is not displayed in the note templates dialog.(using IE11)

### ISSUE THREAD

**Issue by yui-har** [akiko-pusu/redmine_issue_templates#270]
## Summary
In IE11, the note templates dialog is displayed but the template lists are not displayed in `div.filtered_templates_list`. ( /note_templates/list_templates )

## Description
Major browsers other than IE11 will work. (Firefox, Chrome, Safari, Edge)
I think that's because `Element.closest()` doesn't work in IE11.
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Browser_compatibility

## Environment
- Redmine version 4.0-stable

**Comment by akiko-pusu** [comment]
Hi, @yui-har 
Thanks for this reporting. This is quite helpful for me.
(Since note_template, I’m trying not to use jQuery..... So, closest() does not work in IE11.)
I’m going to fix with some workaround.

**Comment by akiko-pusu** [comment]
@yui-har 
Could you help me to confirm this polyfill is effective or not?
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill

Of course, I’m going to confirm / reproduce this issue with using IE11, but need some time to setup IE11 env.

**Comment by akiko-pusu** [comment]
I confirmed the polyfill code is effective.
Now workaround code is included in develop branch. Soon release this.

**Comment by yui-har** [comment]
I have confirmed that it works without problems. Thank you very much.

**Comment by akiko-pusu** [comment]
ありがとうございます！
