### ISSUE TITLE
Comment template insertion does not work.

### ISSUE THREAD

**Issue by MOTOJI-HARADA** [akiko-pusu/redmine_issue_templates#279]
![template_list](https://user-images.githubusercontent.com/54516131/63900581-e37cd100-ca3b-11e9-85d5-e3b950f3981e.png)
![dialog_for_comment_template](https://user-images.githubusercontent.com/54516131/63900585-e677c180-ca3b-11e9-8e1a-c490353aabc0.png)
[production.log](https://github.com/akiko-pusu/redmine_issue_templates/files/3553301/production.log)

## Acknowledgments and background of this issue

Hi! Akiko-san,

We are using your plugin on our Redmine. This plugin is very useful for ticket entry. Thank you very much.

Well, recently, we started to consider updating the redmine_issue_templates plugin with our Redmine updates.
The latest plugins have been able to apply templates to comments, and we tried to validate this feature on out test environment. However, as we can not apply the template as we would like, we will report here along with your template.

I'm very sorry to bother you, but I would appreciate it if you read it and respond to this issue.

## Summary

Applying a template to a comment does not work.
The template for the time of ticket creation, which has been functioning up to now, works without any problem.

### Preparation

1. Set a template for comments from the URL of https://exsample.com/RM3_4.0/projects/pxxxx/settings/issue_templates in advance.
2. A preview of the template registered on the list screen is displayed to confirm that the registration was successful.
   Also check that the registered template is set to be valid

### Steps to reproduce this issue

1. Open any ticket in a template enabled project
2. Click on the edit link
3. Click "Confirm the contents of the template(テンプレートの内容を確認)" to the right of "the template for comment(コメント用テンプレート)" at the top of the note column
4. Click "Apply(適用)" in the dialog that appears

## Environment

- Redmine version :
  4.0.3.stable.18173
- Installed plugins : 0.3.2
- Ruby version : 2.6.3-p62 (2019-04-16) [x86_64-linux]
- OS Platform : CentOS Linux release 7.4.1708 (Core)
- Database (MariaDB, MySQL, PostgreSQL) and its version : psql (PostgreSQL)
9.6.8
- Rails Env : 5.2.3

## Visual Proof / Screenshot

When reporting an application error, post the error stack trace that you should find in the **log file** (eg. log/production.log).

Screen shot would be also helpful.

- Here is a screenshot of list for comment template.
  - It seems that templates are registered successfully.

![template_list](/template_list.png)

- Here is a screen shot of dialog for comment template.
  - If you click "Apply(適用)" on this dialog, nothing is happen and dialog disappears.
  - Registered templates are not inserted to form. 

![dialog_for_comment_template](/dialog_for_comment_template.png)

## LogFile

- "log/production.log" is attached to this issue.
- However, the error-like log description was not found. Since there is no error at the time of the phenomenon, and there is no change at all, we assume that there is no special error information in the log.

## Expected Results

The template is inserted in the note field

## Actual Results

The dialog disappears, but nothing happens and no template is inserted in the note field

## Workaround

Sorry to trouble you, but we can find no workaround for this issue. 

## Our analysis results on this phenomenon

Our technical adviser (Agileware Inc.) has commented as follows about the cause of this phenomenon.

> It is likely that the current redmine_issue_templates plugin does not support URLs in a format such as `https: //redmine.server/folder`.
> More specifically, when you select a template, a JavaScript POST request is sent to the server.
> The destination of this POST request is specified as follows:
> `req.open ('POST', '/ note_templates / load', true);`
> From here, our technical adviser pointed out that this plugin implicitly assumes  access for `https: //redmine.server/`. So, there are possibility that the template can not be applied to the comment in some cases.

Currently, we do not have plans to launch this feature immediately, so there is no urgent need for a fix, but we hope that you will be able to do so **if you can spare your time.**
![template_list](https://user-images.githubusercontent.com/54516131/63900679-48382b80-ca3c-11e9-894d-307babfd63fb.png)
![dialog_for_comment_template](https://user-images.githubusercontent.com/54516131/63900687-4cfcdf80-ca3c-11e9-86f4-7f2315032d87.png)
[production.log](https://github.com/akiko-pusu/redmine_issue_templates/files/3553305/production.log)

**Comment by ishikawa999** [comment]
@MOTOJI-HARADA 
This bug report text is very kind and nice! :smile:

I think this issue is related to the issue I created earlier.
"The note_template can not be applied due to the hard coding of the URL if Redmine running in a subdirectory. #260 "

#260 issue has been corrected 0.3.5.
Would it be possible for you to upgrade the plugin version?

**Comment by MOTOJI-HARADA** [comment]
@ishikawa999 
Thanks for your strong support.

I try plugin version 0.3.5.
I will report on the results.

**Comment by MOTOJI-HARADA** [comment]
@ishikawa999 
It's work it!
Thank you very much!

**Comment by MOTOJI-HARADA** [comment]
This issue has been resolved and will close.

**Comment by ishikawa999** [comment]
@MOTOJI-HARADA 
I'm glad that I could help you out.
Thank you!
