### ISSUE TITLE
Project Settingでの他プラグインとの干渉

### ISSUE THREAD

**Issue by sallybird** [akiko-pusu/redmine_issue_templates#282]
This is a template to report bug related to redmine issue templates plugin.
You can fill in any format, free style in case report features or questions.

## Summary
ProjectSettingにタブを追加するほかのプラグインとの干渉が見られました。

/lib/issue_templates/projects\helper_patch.rb

末行を以下に書き換えると干渉がなくなりました。

`
ProjectsHelper.prepend(IssueTemplates::ProjectsHelperPatch)
`

## Environment

These informations are greatly helpful to support quickly.
You can get these informations from Redmine's information page.
(E.g. http://example.com/admin/info)

- Redmine version 4.0.4
- Installed plugins Wiki-extention,Webhook etc
- Ruby version 2.5.5
- OS Platform 
- MySQL
- Rails Env 5.2.3

**Comment by qmotas** [comment]
私もredmine_webhookとの組み合わせで同様の事象が発生しています。

本プラグインより後に読み込まれるプラグインで`ProjectsHelper.prepend()`を使用してプロジェクト設定のタブを拡張している場合、これが反映されないようです。

ワークアラウンドとして、プラグイン名を変更（ディレクトリ名と、init.rbで`Redmine::Plugin.register`している名称）してプラグインの読込順を変更することでタブが表示されるようになりました。
ご参考まで。

**Comment by akiko-pusu** [comment]
@qmotas さん
こんにちは、レポートありがとうございます！

> プラグイン名を変更（ディレクトリ名と、init.rbでRedmine::Plugin.registerしている名称）

プラグインの干渉に慣れていない方にとっては、これはちょっと避けたい方法ですよね...。
組み合わせの情報は貴重なので、ソースがオープンになっているものに関しては再現性を確認してみます。

**Comment by akiko-pusu** [comment]
プロジェクト単位のIssueTemplateは、Project Setting Tabからの導線のほかに、チケット一覧のサイドバーからも辿れるので、干渉が多いなら別の方向で導線を設定するように検討しますね！

**Comment by akiko-pusu** [comment]
確認中、まだ手元で再現できていません。

**Comment by akiko-pusu** [comment]
@sallybird @qmotas 
遅くなりまして申し訳ございません。ただいま再現性を確認しているのですが、状況を正確に確認させていただけますか？

「干渉」の結果、**Issue Templateのタブが見えなくなる**のか、それとも**Wiki ExtやWebhookのタブが見えなくなる**のか、どちらでしょうか？

ただいまTemplateとWiki Extをチェックしていて、Template側が表示されていてWiki Extが表示されていないのを確認しました。
この現象でよろしいでしょうか？

<img width="728" alt="tobe" src="https://user-images.githubusercontent.com/122621/69898951-52532880-13a3-11ea-91d0-de87e2624fb6.png">

**Comment by akiko-pusu** [comment]
こちらのIssueとの兼ね合いで対応したため、全て組み合わせて確認: #217

**Comment by akiko-pusu** [comment]
いくつかのプラグインと組み合わせをして検証しました。
キャプチャに添えたプラグインを利用して、問題がないところまで調整をします。

バグになりますので、リリースタグは後から打ちますが、先にmasterにマージさせる予定です。

Hi, thank you so much for your information.
I've just confirmed and try to add workaround for this issue. (PR: #292)

Maybe this is effective.

Also, I've modified my plugin named "Banner".
-  https://github.com/akiko-pusu/redmine_banner/pull/120

Here are my confirmation screenshots.

<img width="561" alt="my_plugins_and_env" src="https://user-images.githubusercontent.com/122621/69900796-728ee180-13bb-11ea-9237-425e05145803.png">

<img width="785" alt="after-fixed" src="https://user-images.githubusercontent.com/122621/69900794-6d319700-13bb-11ea-9b27-8197ae37cedd.png">

**Comment by akiko-pusu** [comment]
Issue Template plugin 0.3.6 was released, including the workaround for this issue.
If you use Banner plugin, please update the Banner plugin to 0.2.2.

**Comment by qmotas** [comment]
>「干渉」の結果、Issue Templateのタブが見えなくなるのか、それともWiki ExtやWebhookのタブが見えなくなるのか、どちらでしょうか？

私のケースは「プロジェクトの設定画面(`/projects/foo/settings`)でIssue Templateのタブは見えるがredmine_webhookのタブが見えなくなる」という事象でした。
後日0.3.6にアップデートしてみます、ありがとうございます！

**Comment by akiko-pusu** [comment]
@qmotas ありがとうございます。こちらも、検証の結果、同じくIssueTemplateのタブは見えて、Wiki ExtとWebhookが見えない状態になりました。
再現の上での修正をしましたので、なんとかなるかと思います。

もし入れ替えできない場合は、この部分だけ変更をして試してみてくださいませ。

https://github.com/akiko-pusu/redmine_issue_templates/pull/292/files#diff-9146b47933f8c15b07964896ffa789abL18-R20

```diff
- ProjectsController.helper(IssueTemplates::ProjectsHelperPatch)
+ ProjectsHelper.prepend(IssueTemplates::ProjectsHelperPatch) unless ProjectsHelper.included_modules.include?(IssueTemplates::ProjectsHelperPatch)
```

**Comment by qmotas** [comment]
@akiko-pusu 
ご報告が遅くなりましたが、0.3.6とredmine_webhookとの組み合わせでプロジェクトの設定画面にIssue Template、Webhook両方のタブが表示されることを確認致しました。
ご対応ありがとうございました！ :pray:
