### ISSUE TITLE
Checklists not working after changing issue type

### ISSUE THREAD

**Issue by mkay82** [akiko-pusu/redmine_issue_templates#286]
## Summary
Checklists not working after changing issue type

## Description
Checlists only works with default task type. If we want to assign template to other types, then checklists aren't rendered properly. Also - if we've got template with checklist assigned to default task type, but we change type to something else and then change it back to default one, checklists don't work anymore. 

## Environment
Environment:
  Redmine version                4.0.4.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                sendmail
SCM:
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  easy_gantt                     1.12
  redmine_checklists             3.1.16
  redmine_default_due_date       0.0.1
  redmine_home_page_redirector   1.0.0
  redmine_issue_templates        0.3.5
  redmine_percent_done           1.1.0

## Expected Results
checklists should work for all task types;)

## Actual Results
on 'new task' page only the first item from checklist is displayed. checklist isn't created at all with created task
 
## Workaround
use templates with checklist only in default task type

**Comment by akiko-pusu** [comment]
Hi, @mkay82 
Thanks for using my plugin.

Let me confirm:

1. Each template should have its own definition:
Each template related to an issue type (tracker) should have its own checklists definition.
Even If the default template has some checklists definition,  another template does not inherit that definition.

2. Checklist support is the optional and trial feature 

Do you use the free version of redmine_checklists or pro? (Free or Paid?)
If you use the pro version, I think you can use the checklist's own template feature.

And, in fact, my checklist plug-in support is not the responsibility of this plug-in. 
This is an optional feature. 
If something inconvenient, I'm going to remove this feature.

**Comment by mkay82** [comment]
Hi @akiko-pusu ,
thank you for quick resposnse. 

I think you didn't understand correctly my description. Let me give you example. Let's say i've got 2 trackers in my project named: "task" and "bug" and "task" is default one, which is opened when i want to create new issue. Let's also say that i've created 2 templates - both with checklist - "task template" (related to "task:) and "bug template" (related to "bug").

In that scenario:
1. If i create new issue from "task" tracker using "task template" - checklists are rendered properly
2. If i create new issue from "bug" tracker using "bug template" - checklists aren't added to my new issue
3. If (during entering new issue) i change tracker type from "task" to "bug" and then change it back to "task" - checklists won't be added to my new issue (exactly the same behavior ans in p. 2)

PS: please - don't remove this feature from plugin. it's really cool and helpfull;/

**Comment by akiko-pusu** [comment]
Sorry I could not reproduce this situation.
Here is my screen capture. 

![issue-template](https://user-images.githubusercontent.com/122621/69906940-d7275c00-140e-11ea-89c0-eba2d33f22fa.gif)

- Create a template for tracker: Bug with 3 checklists.
  - Bug tracker is the default tracker of my project.
- Create a template for tracker: Feature with 2 checklists.
- Then, go to the "new issue" page.
- First, the Bug tracker is loaded, and then the template is loaded with 3 checklists.
- After that, change the tracker to Feature. Then the template for Feature is loaded with 2 checklists.

Is there another action in your environment?
Is this behavior different from what you expect?

Please make sure your browser has a JavaScript error.

---------------

** My env **

```
Environment:
  Redmine version                4.0.5.devel.18928
  Ruby version                   2.5.3-p105 (2018-10-18) [x86_64-darwin18]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               SQLite
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Git                            2.21.0
  Filesystem                     
Redmine plugins:
  redmine_banner                 0.2.1
  redmine_checklists             3.1.16
  redmine_issue_templates        0.3.5
  redmine_webhook                0.0.5
  redmine_wiki_extensions        0.9.0
```

<img width="756" alt="redmine_info" src="https://user-images.githubusercontent.com/122621/69907020-684b0280-1410-11ea-9e01-f7bb4952acbb.png">

**Comment by mkay82** [comment]
Hi,
i've just checked again and.... it's working correctly now...

i think it has to be something with our instalation - we've made a lot of server tasks recently (including updating and moving services from one server to another - redmine was also moved to different server in meantime).

so this should propably be closed. sorry for bothering you

**Comment by akiko-pusu** [comment]
@mkay82 
I'm glad to hear that!
And since I haven't used Redmine in a production environment for a long time, any information is very valuable to me.

Thank you for using my plugin!
