### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by ryoji-takeuchi** [akiko-pusu/redmine_issue_templates#287]
##  Summary
Internal server error 500 occurred when save new issue template.

## Description
Wen push create button after fill issue template form, Internal server error 500 occurred 

## Environment
- Redmine version 4.0.4
- Rails version 5.2
- Database : My SQL
- Installed Plugins
   Lychee
   DMSF
   Redmine Wiki Lists

Logfile:

Started POST "/projects/1tetsu_mstest/issue_templates" for 133.113.6.220 at 2019-10-10 17:03:14 +0900
Processing by IssueTemplatesController#create as HTML
  Parameters: {"utf8"=>"?", "authenticity_token"=>"xxx", "issue_template"=>{"title"=>"T_工程管理", "tracker_id"=>"184", "issue_title"=>"", "description"=>"*エビデンス*", "note"=>"", "is_default"=>"0", "enabled"=>"0", "enabled_sharing"=>"0"}, "commit"=>"作成", "project_id"=>"1tetsu_mstest"}
  Current user: d8122510 (id=26)
Completed 500 Internal Server Error in 46ms (ActiveRecord: 8.7ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Incorrect string value: '\xE5\xB7\xA5\xE7\xA8\x8B...' for column 'title' at row 1: INSERT INTO `issue_templates` (`title`, `project_id`, `tracker_id`, `author_id`, `note`, `description`, `created_on`, `updated_on`, `issue_title`) VALUES ('T_工
程管理', 401, 184, 26, '', '*エビデンス*', '2019-10-10 17:03:14', '2019-10-10 17:03:14', '')):

##Other information
When I installed "Default custom query" plugin, internal server error 500 also occurred when setting tub has been opened.  I ask to default custom query owner, he said DMSF may cause the issue because DMSF changed alias_method_chain as following.
>alias_method_chain has been replaced with prepend. Not directly but using >RedmineExtensions::PatchManager. Consequently, there might occure conficts with plugins >which overwrite the same methods.
https://github.com/danmunn/redmine_dmsf/blob/master/CHANGELOG.md#161-2018-04-03

Thank you for the report.

Maybe this is not a bug in DefaultCustomQuery. I think that it is a coding mistake of other plug-ins.
An error occurs if the following code exists:

https://github.com/danmunn/redmine_dmsf/blob/1d63ce0ee72d8cd723448d6a21000e5486bbb3c8/lib/redmine_dmsf/patches/projects_helper_patch.rb#L29

>This is not an appropriate code for module (patch) to include to ProjectsHelper.
>Although it is described in the DMSF CHANGELOG as follows, it is preferable that we do not call super which is not present in class by alias_method etc.
>
>https://github.com/danmunn/redmine_dmsf/blob/master/CHANGELOG.md#161-2018-04-03
>
>Thanks.
https://github.com/hidakatsuya/redmine_default_custom_query/issues/37

Thanks!!

**Comment by akiko-pusu** [comment]
@ryoji-takeuchi 
Hi, thanks for using my plugin.

Is this your first time setting up or running Redmine?
I think this is not a bug caused by all the plugins, including my plugin.

Maybe this trouble is due to your database condition.

If you understand Japanese, please see this article.
https://qiita.com/tomaaaaaaaaa/items/08ce75b95df3d310817a

And please confirm your database encoding.

**Comment by akiko-pusu** [comment]
@ryoji-takeuchi How is your situation?  I think this is not a bug.

**Comment by ryoji-takeuchi** [comment]
Thank you for your advice. I found My SQL DB charset is not correct as following.

+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
So, I try to rebuild DB as following

下記の手順を試みてもよいでしょうか 
•	一旦データベースのバクアップをlatin1指定/utf8指定の両方で取得
•	my.confのcharacter_set_serverをutf8に変更してmysql再起動
•	現在のDBをドロップ
•	新しくDBを作成。ここで、character_set_database がutf8になっていることを確認
•	バックアップからリストア

Thanks!!

**Comment by ryoji-takeuchi** [comment]
Thanks for your great support. 
I changed charset and restore DB then uninstall issue template plugin and install issue template plugin again.
After restart Redmine, issue template plugin work normally.
Your precise advice is very helpful for us.
I have confirmed this issue is not bug of issue template plugin. So I would like close this issue.
Thank you very much!!

**Comment by akiko-pusu** [comment]
@ryoji-takeuchi  Great!
ありがとうございました！
日本語のメッセージでも勿論だいじょうぶです！(お手数かけていただいて恐縮です）
