### ISSUE TITLE
JS is failing to find issue_tracker_id

### ISSUE THREAD

**Issue by dmakurin** [akiko-pusu/redmine_issue_templates#288]
We've been adding a bunch of note templates for a project. Then on edit issue page pressing button "show" to show note templates. However the list is empty, browser console was showing an error:
```
Uncaught TypeError: Cannot read property 'options' of null
    at HTMLAnchorElement.<anonymous> (43108:947)
```

The error in [line](https://github.com/akiko-pusu/redmine_issue_templates/blob/master/app/views/issue_templates/_note_form.html.erb#L67) .

So exactly what caused the error. User has no permission to edit 'tracker' field on edit page therefore object 'issue_tracker_id' does not exist in dom, JS failed to find out tracker ID and create a request to the server.

Steps to reproduce:
1. Create project
2. Add some trackers
3. Add note template
4. Set up redmine permission to roles so user **will be able to edit issue** but **won't be able to change 'Tracker' field**

Quick workaround:
```
Index: app/views/issue_templates/_note_form.html.erb
<+>UTF-8
===================================================================
--- app/views/issue_templates/_note_form.html.erb	(revision 743ab910e713c5cc1d74678682bd5cf2460048df)
+++ app/views/issue_templates/_note_form.html.erb	(date 1571058729937)
@@ -3,7 +3,8 @@
   if type == 'template_edit_journal'
     element_id = "template_journal_#{@journal.id}_notes"
   end
-  project_id = issue.try(:project_id)
+  project_id = issue&.project_id
+  tracker_id = issue&.tracker_id
 %>
 <div id="<%= element_id %>">
   <label for="select_note_template" style="font-weight: bold;">
@@ -63,11 +64,8 @@
 // Show dialog
 var dialog_link = document.getElementById('link_<%= element_id %>_dialog');
 dialog_link.addEventListener("click",function() {
-  var target = document.getElementById('issue_tracker_id');
-  var tracker_id = target.options[target.selectedIndex].value;
   var template_list_url = '<%= url_for(controller: 'note_templates',
-        action:'list_templates', project_id: project_id) %>'
-        + '&tracker_id=' + tracker_id;
+        action:'list_templates', project_id: project_id, tracker_id: tracker_id) %>';
   var token = document.querySelectorAll('#issue-form input[name="authenticity_token"]')[0];
 
   var req = new XMLHttpRequest();

```

**Comment by akiko-pusu** [comment]
@dmakurin Thaks for your using my plugin, and reporting this issue.
I'll confirm the situation as soon as possible.
Also I really appreciate above your patch. It's very helpful!

**Comment by akiko-pusu** [comment]
Also merged into master. Thanks!
