### ISSUE TITLE
Templates not correctly shown after changing project

### ISSUE THREAD

**Issue by vibp** [akiko-pusu/redmine_issue_templates#289]
##Description

After clicking on new issue, if you realise you are in the wrong project, and decide to change it on the "new issue" form, itself instead of using the project list at the top right corner, the list of templates does not get updated and you still see the templates of the general active project.

See screenshot. IT is our main Project. Promt is a subproject. Promt only has two templates, which only are show if Promt is selected before I click on new issue. If I click on new issue and then change the project on the new issue form, the templates shown are still those from the project IT

## Environment
- Redmine version:  4.0.4.stable
- Installed plugins:
  a_common_libs              2.5.5
  easy_gantt                     1.12
  easy_mindmup               1.0
  easy_wbs                        1.5
  redmine_base_deface      1.3.2
  redmine_editauthor         0.11.0
  redmine_issue_tabs         1.3.4
  redmine_issue_templates 0.3.4
  redmine_refresh               0.2.0
- Ruby version: 2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
- OS Platform: Debian 9
- Database: MariaDB 10.4.8
- Rails Env 5.2.3

## Visual Proof / Screenshot
![redminetemplates](https://user-images.githubusercontent.com/31411402/67406374-4612c900-f5b6-11e9-96dc-9f73eea971ee.png)

## Expected Results

The templates of the subproject should be shown

## Actual Results

The field "templates"  ignores changes in the field "project" and keeps on showing templates from the general active project.

## Workaround
Select the project before creating the issue. But this makes the project selector inside the New issue form useless.

**Comment by akiko-pusu** [comment]
Hi, please confirm these points:

- Is your parent project: "IT" template marked "**Enabled sharing with project tree**."?
- Is your child project: "Promt" template marked "Enabled"?
  - Is your child project:  "Promt" template setting marked "**Inherit templates**" ?

Please confirm your project settings for Issue Template (E.g. /projects/promt/settings/issue_templates)

If **Inherit templates** is marked, the templates of parent projects are shared with child project.

Here is the sample capture in case not to Inherit templates of parent templates.

![issue-new](https://user-images.githubusercontent.com/122621/69907933-bff26980-1422-11ea-818a-36e49c7b90e5.gif)

**Comment by akiko-pusu** [comment]
@vibp Ok, I've confirmed the situation.

- Go to parent project and new issue page. (exp. /projects/it/issues/new)
- Change the project to subproject ("Promt")
  - Epected: Templates for Promt will be shown.
  - Result: Templates for IT are shown.

Though I have to write the test code to confirm, but this workaround might be effective.
Please try:

```diff
diff --git a/lib/issue_templates/issues_hook.rb b/lib/issue_templates/issues_hook.rb
index 61c6358..2b588a6 100644
--- a/lib/issue_templates/issues_hook.rb
+++ b/lib/issue_templates/issues_hook.rb
@@ -24,7 +24,7 @@ module IssueTemplates
       return if copied_issue?(parameters)

       project = context[:project]
-      project_id = project.present? ? project.id : issue.project_id
+      project_id = issue.project_id.present? ? issue.project_id : project.id
       return unless create_action?(parameters[:action]) && project_id.present?
```

**Comment by akiko-pusu** [comment]
Hi, I've released including this workaround. I hope it would be any help.

**Comment by vibp** [comment]
Dear akiko-pusu,

Sorry for my absence. I have been on holidays during the last few weeks and haven't read the e-mails from work.

I am happy to see that you have managed to find the issue. I will test it out at some point this week and let you know how it goes.

Have a nice day
