### ISSUE TITLE
Uncaught exception: cannot load such file -- issue_templates/issues_hook

### ISSUE THREAD

**Issue by DanieliMi** [akiko-pusu/redmine_issue_templates#297]
## Description
When executing `rake redmine:plugins:migrate RAILS_ENV=production` to install the plugin it fails with the following error message:  
```
rake aborted!
LoadError: cannot load such file -- issue_templates/issues_hook
/home/user/projects/tracker/plugins/redmine_issue_templates/init.rb:22:in `<top (required)>'
/home/user/projects/tracker/plugins/easyproject/init.rb:463:in `load_plugin_init'
/home/user/projects/tracker/plugins/easyproject/init.rb:449:in `block in load_all_plugins'
/home/user/projects/tracker/plugins/easyproject/init.rb:448:in `each'
/home/user/projects/tracker/plugins/easyproject/init.rb:448:in `load_all_plugins'
/home/user/projects/tracker/plugins/easyproject/init.rb:417:in `init!'
/home/user/projects/tracker/plugins/easyproject/init.rb:473:in `<top (required)>'
/home/user/projects/tracker/config/initializers/22-change_plugins_order.rb:15:in `load'
/home/user/projects/tracker/config/initializers/30-redmine.rb:21:in `<top (required)>'
/home/user/projects/tracker/config/environment.rb:14:in `<top (required)>'
/home/user/projects/tracker/lib/tasks/redmine.rake:57:in `block (2 levels) in <top (required)>'
/home/user/.rbenv/versions/2.5.7/bin/bundle:23:in `load'
/home/user/.rbenv/versions/2.5.7/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```
When commenting the requires it works but obviously the hooks to actually select the templates won't work.

Is there any way to debug this issue?

## Environment
Easy Redmine:
  Brand version                  ER 2019
  Platform version               08.10
  Build version                  (build not detected)
  Full version                   ER 2019 (Platform: 08.10)
Environment:
  Redmine version                4.0.5.stable
  Ruby version                   2.5.7-p206 (2019-10-01) [x86_64-linux]
  Rails version                  5.2.3
  Environment                    development
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.3
  Mercurial                      3.7.3
  Git                            2.24.0
  Filesystem                     
Redmine plugins:
  before_render                  
  ckeditor                       
  clipboard_image_paste          1.9
  sanitize                       
  easy_extensions                2019
  easy_agile_board               2019
  easy_alerts                    2019
  easy_attendances               2019
  easy_budgetsheet               2019
  easy_buttons                   2019
  easy_calendar                  2019
  easy_contacts                  2019
  easy_custom_field_permissions  2019
  easy_data_templates            2019
  easy_money                     2019
  easy_printable_templates       2019
  easy_project_attachments       2019
  easy_quick_project_planner     2019
  easy_redmine                   
  easy_theme_designer            2019
  easy_to_do_list                2019
  easy_xml_helper                2019
  easy_baseline                  1.3
  easy_checklist                 2019
  easy_gantt                     1.9
  easy_gantt_pro                 1.9
  easy_gantt_resources           1.6
  easy_instant_messages          2016
  easy_job                       1.1
  easy_mindmup                   1.2
  easy_resource_base             1.0
  easy_wbs                       1.6
  easy_zoom                      2019
  redmine_issue_templates        0.3.6
  redmine_test_cases             2019-03-18
Server:
  Current datetime               2019-12-04 18:00:52 +0100
  Server datetime                2019-12-04 18:00:52 +0100
  Database encoding              utf8mb4 / utf8mb4_general_ci

**Comment by akiko-pusu** [comment]
Hi, @DanieliMi 
I could not reproduce this situation and now it's quite hard for me to confirm the problem because there are so many plugins you use. (Including commercial ones?)

1st, please confirm the installation.
Ref. https://github.com/akiko-pusu/redmine_issue_templates/blob/master/README.md#plugin-installation.

For instance, if the plugin's directory name is different it may cause some errors.

> Please note that plugin's folder name should be "redmine_issue_templates". 
> If changed, some migration task will be failed.



Does the problem occur in case you use the previous version of Issue Template plugins?
You can download or confirm the difference from here:
https://github.com/akiko-pusu/redmine_issue_templates/releases
(Zip file)

**Comment by akiko-pusu** [comment]
I think this is related to Easy Redmine. 
Because the original Redmine (including 4.0.5-stable)  does not have the file such as ``config/initializers/22-change_plugins_order.rb``.

Could you attache above file's source code?
Or I think it's better for you to ask your Easy Redmine's vendor to support.

**Comment by DanieliMi** [comment]
Installation is not possible due to the error that it can't find the files in `lib/issue_templates`. However if the requires in `plugins/redmine_issue_templates/init.rb:22-24` are commented the migration works but the select when creating an issue is not showing up due to the missing hooks.

> Does the problem occur in case you use the previous version of Issue Template plugins?
I've tried `master`, `0.3.6`, `0.3.0` and `0.2.1` and they don't work.

> I think this is related to Easy Redmine.

I was afraid this might be the cause. I'll contact the EasyRedmine support and see if they can help me further. Maybe we can find a way for the Plugin to work with both Redmine and EasyRemine.

**Comment by DanieliMi** [comment]
Your hint of the `config/initializers/22-change_plugins_order.rb` did the job I've actually found the problem. Easyredmine doesnt use `Redmine::Plugin::load` it's overwriting it and handling the loading of plugins itself to manipulate it. And within they require the `init.rb` of the plugins but they're not adding the `lib/` directive to `ActiveSupport::Dependencies.autoload_paths`

For anyone else with EasyRedmine and this problems a workaround is to add the following to `EasyProjectLoader::load_plugin_init` before the `require initializer`
```ruby
if File.directory?(plugin_path.to_path)
  lib = File.join(plugin_path.to_path, "lib")
  if File.directory?(lib)
    $:.unshift lib
    ActiveSupport::Dependencies.autoload_paths += [lib]
  end
end
```

Maybe I can talk to the support and figure out why they're leaving this part out and maybe they can add it.

**Comment by akiko-pusu** [comment]
@DanieliMi 
Thanks for your valuable information! 
It's quite important information for other users.

Of course, I do everything I could to support you :)
If your situation is changed, feel free to report again.

**Comment by DanieliMi** [comment]
I think it should be working for now I've created a [gist](https://gist.github.com/DanieliMi/5abd682fa4c8b9ac28f6050e75675eb8) with the patches I had to apply in case anyone needs them.

**Comment by akiko-pusu** [comment]
@DanieliMi 
Thank you so much for the above gist script!

After this issue was closed, I tried to change the way to access the issue template menu.

On Dec 8, lates release v0.3.7 has been released.
Maybe this kind of conflict does not occur.  

Please see more details:
https://github.com/akiko-pusu/redmine_issue_templates/releases/tag/0.3.7

I hope this would be any help!

**Comment by DanieliMi** [comment]
You're very welcome! I currently have another issue to do with the EasyRedmine version. jQuery is loaded differently and due to it it is not available when [issue_templates.js](https://github.com/akiko-pusu/redmine_issue_templates/blob/master/assets/javascripts/issue_templates.js) is loaded. I've not come to a solution for this yet and I've currently not the time but once I found a solution I'll provide as well so EasyRedmine users may use this plugin with it's full potential.

**Comment by akiko-pusu** [comment]
> jQuery is loaded differently and due to it it is not available when issue_templates.js is loaded.

Thanks again.
I welcome your suggestion, information and so on.
Of course, I really happy if my plugin could be used and any help for Easy Redmine's users.
Not only you but also ER's staffs suggestions are highly welcomed.
