### ISSUE TITLE
Add preselected watchers to templates

### ISSUE THREAD

**Issue by mekatum** [akiko-pusu/redmine_issue_templates#302]
Hi!
Thanks you for your work!

Can you add ability add preselected watchers to templates? I would like to add new issue in my redmine with preselected watchers.

**Comment by akiko-pusu** [comment]
@mekatum 
Thanks for your request.

I think your request is related to this issue:
https://www.redmine.org/issues/8568

**Comment by akiko-pusu** [comment]
Implemented on #361 
Please note, selecting watchers is only for project scope template.
