### ISSUE TITLE
Default templates aren't filled in for non-default tracker

### ISSUE THREAD

**Issue by Hnasar** [akiko-pusu/redmine_issue_templates#311]
## Summary

If I have a default template for Bug, when I select bug, the fields aren't filled in.

## Environment

This is a brand new VM with a fresh database.
```
Environment:
  Redmine version                4.0.4.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.5.1
  redmine_issue_templates        0.3.5
  redmine_smile_togglesidebar    1.0.6
  redmineup_tags                 2.0.8
```
### Regression info

This used to work fine, on my old production instance
```
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  4.2.11
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.5
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  add_assignee_to_watchers       0.0.2
  redmine_agile                  1.4.12
  redmine_issue_templates        0.2.2-dev
  redmine_smile_togglesidebar    1.0.6
  redmineup_tags                 2.0.8
```

## Visual Proof / Screenshot

No errors in the logs
![issue-template-bug](https://user-images.githubusercontent.com/463274/73310558-8192e400-41f2-11ea-96d1-8e29efda8139.gif)

## Expected Results

Field is filled in.

## Actual Results

Nothing is filled in.

## Workaround

N/A
I tried setting this per-project, global, and checking/unchecking 'Replace subject in description'
Same with chrome and firefox

**Comment by Hnasar** [comment]
nevermind I think it was an SSL issue...

**Comment by akiko-pusu** [comment]
@Hnasar 
Thanks for using my plugin!
I really appreciated that your environment information between Redmine3.x and Redmine4.x.

> nevermind I think it was an SSL issue...

Ok, is there other problem?
I can support as possible as I can.

Please note: latest veesion of issue template is now v1.0.0.
As I wrote at README, v1.0.0 does not support IE11.
So, if your members use IE11, I **highly recommend to use v0.3.7** as stable release.

Please  feel free to report your comment!
