### ISSUE TITLE
Unable to preview template with Firefox

### ISSUE THREAD

**Issue by vividtone** [akiko-pusu/redmine_issue_templates#317]
## Summary

You cannot preview a template if your web browser is Firefox. No problem with Chrome. See the image below. The preview tooltip is cropped by the table.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/114863/73828523-bd5a2900-4844-11ea-9a72-fb0e4643dc8c.png">

## Environment

- Redmine version: trunk (r19495)
- Ruby version: Ruby 2.6.5
- OS Platform: macOS Mojave 10.14.6
- Database: sqlite3
- Rails Env: development

**Comment by akiko-pusu** [comment]
Thanks! I'll confirm this.

**Comment by akiko-pusu** [comment]
I could confirmed and reproduced this problem.
Both v0.3.7 (even stable) and 1.0.0 (master).

Tooltip for help is not affected.
Template list (index) and Preview template (popup) should be fixed.

**Comment by akiko-pusu** [comment]
Fixed and merged into master (and 0.3-stable branch). Thanks for your support!

**PC View**

<img width="639" alt="normal-view" src="https://user-images.githubusercontent.com/122621/74094874-a577f300-4b2b-11ea-9ac1-f609d607eaaf.png">

**Responsive View**

<img width="548" alt="responsive-view" src="https://user-images.githubusercontent.com/122621/74094882-b9235980-4b2b-11ea-8cad-402e2d138ac8.png">

The same problem for the ``preview template (popup)``  is also fixed.
