### ISSUE TITLE
Can't create/update Note Templates

### ISSUE THREAD

**Issue by AlUser71** [akiko-pusu/redmine_issue_templates#323]
## Summary
I can't create new or update existing Note Templates in version 1.0.0

## Description
When I try to create a note template for a tracker, this operation fails if the template becomes a certain length.

I can't specify the amount of charactes but if you just add some piece of lines (3-4) with less than ~100 characters there is no problem.
If I try to add longer template text, it can't be saved an an error page will be displayed.
e.g. a template text with 20 lines and 861 characters can't be saved.

## Environment
System info: | Linux redmine-playground 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Environment:
  Redmine version                4.0.4.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.7
  Mercurial                      4.5.3
  Cvs                            1.12.13
  Bazaar                         2.8.0
  Git                            2.17.1
  Filesystem                     
  GitMirror                      2.17.1
Redmine plugins:
  additionals                    2.0.22-1
  easy_gantt                     1.12
  easy_mindmup                   1.0
  easy_wbs                       1.5
  redmine_agile                  1.5.2
  redmine_banner                 0.3.1
  redmine_checklists             3.1.17
  redmine_dmsf                   2.4.1
  redmine_favorite_projects      2.1.0
  redmine_git_mirror             0.8.0
  redmine_issue_templates        1.0.0
  redmine_questions              1.0.1
  redmine_resources              1.0.2
  redmine_smile_togglesidebar    1.0.7
  redmine_wiki_lists             0.0.9
  redmine_wysiwyg_editor         0.13.0
  redmine_xlsx_format_issue_exporter 0.1.6
  redmine_zenedit                1.0.3

## Visual Proof / Screenshot
[production.log](https://github.com/akiko-pusu/redmine_issue_templates/files/4324187/production.log)
ActiveRecord::ValueTooLong (Mysql2::Error: Data too long for column...

![grafik](https://user-images.githubusercontent.com/60700838/76522441-e2a30e00-6466-11ea-9c04-cf5c63cc1e1f.png)

## Expected Results
New template can be created or existing templates can be edited beyond a certain length.

## Actual Results
No new template can be created and no exisitng templates can be changed beyond a certain length.

## Workaround
none

**Comment by akiko-pusu** [comment]
Hi, @AlUser71 Thanks for this issue.
I'm going to create a migration file to change a column type from string to text.
Please wait for a while.

**Comment by akiko-pusu** [comment]
I've just released v1.0.1, include the migration task.
Could you please apply it?
