### ISSUE TITLE
Please merge "Pull request #324" to 0.3.7

### ISSUE THREAD

**Issue by yui-har** [akiko-pusu/redmine_issue_templates#328]
## Summary

Error "ActiveRecord::RecordNotFound" occurs in `IssueTemplatesSettingsController#edit` method.

## Description

If the following data is configured, executing `IssueTemplatesSettingsController#edit` method with `project_id = 6` will cause an error.

```ruby
irb(main):001:0> IssueTemplateSetting.pluck(:project_id)
=> [1, 2, 3, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25, 26, 6, 5, 27, 28]
irb(main):002:0> IssueTemplateSetting.pluck(:id)
=> [1, 2, 3, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
```

## Workaround

Please merge "Pull request  #324" to 0.3.7(0.3-stable).

**Comment by akiko-pusu** [comment]
Hi, @yui-har 
Thanks for this issue reporting!
I'm going to apply soon into the 0.3-stable branch!

**Comment by akiko-pusu** [comment]
Sorry for my delayed reply.
I've just merged (via cherry-pick) above code and update the test code.

Thanks for your reporting. This is quite helpful for me and greatly appreciate.

**Comment by yui-har** [comment]
I am grateful to you.

**Comment by yui-har** [comment]
Are you planning to release this in 0.3.8?

**Comment by akiko-pusu** [comment]
https://github.com/akiko-pusu/redmine_issue_templates/releases/tag/0.3.8
