### ISSUE TITLE
Plugin changes the appearance of all tables in Redmine

### ISSUE THREAD

**Issue by sandratatarevicova** [akiko-pusu/redmine_issue_templates#332]
## Summary

Plugin changes the appearance of all tables in Redmine.

## Description

The plugin changes the appearance of all tables in Redmine - it adds a border to `table.list`. It is not so visible on the default Redmine theme, but it can be problematic on different themes.

The problematic style was added within commit 022bf7cef135ac222399eb7a3eaf3b29868910e0.

**Comment by akiko-pusu** [comment]
Thanks for your reporting!
I'm going to try fix it.

**Comment by akiko-pusu** [comment]
Workaround: 73985f0
If there is no problem, I'm going to apply this.

**Comment by sandratatarevicova** [comment]
That was fast! Thank you 🙂

**Comment by akiko-pusu** [comment]
Just merged into master branch, thanks for your feedback!
I hope you’re all doing ok & staying safe 😉
