### ISSUE TITLE
Orphaned template list is not displayed

### ISSUE THREAD

**Issue by yui-har** [akiko-pusu/redmine_issue_templates#337]
## Summary

Clicking "Orphaned templates from tracker" link does not show the orphaned template list.

## Description

I clicked on $('#orphaned_template_link') in /projects/:project_id/issue_templates and /global_issue_templates, but nothing changed.

## Environment

- Redmine version
trunk (r19707)
- Installed plugins
redmine_issue_templates: **0.3-stable**
- Ruby version
2.5.8
- Rails Env
development, production

## Workaround

I think the callback function of `ajax:success` is not working properly. I have confirmed that it works with the following patch(confirmed with IE11, Edge, Firefox, Chrome, Safari).

```diff
diff --git a/assets/javascripts/issue_templates.js b/assets/javascripts/issue_templates.js
index 6c9355c..c7aa8e8 100644
--- a/assets/javascripts/issue_templates.js
+++ b/assets/javascripts/issue_templates.js
@@ -348,14 +348,13 @@ $(function () {
     $('a.template-disabled-link').issueTemplate('disabled_link');

     // display orphaned template list
-    $('#orphaned_template_link').on({
-        'ajax:success': (function (_this) {
-            return function (e, data) {
-                $('#orphaned_templates').toggle();
-                return $('#orphaned_templates').html(data);
-            };
-        })(this)
-    });
+    $('#orphaned_template_link').on(
+        'ajax:success', function (e) {
+            var xhr = e.detail[2];
+            $('#orphaned_templates').toggle();
+            $('#orphaned_templates').html(xhr.response);
+        }
+    );
 });

 // for IE11 compatibility (IE11 does not support native Element.closest)
```

**Comment by akiko-pusu** [comment]
Hi, @yui-har 
Thank you so much for your issue reporting and the above patch!
I've just merged it into the 0.3-stable branch.
Also, I'm going to create a tag version0.3.8.
