### ISSUE TITLE
Selecting note template browser "jumps" to top of page

### ISSUE THREAD

**Issue by ChrisUHZ** [akiko-pusu/redmine_issue_templates#338]
## Description
If i select a note template..
![grafik](https://user-images.githubusercontent.com/57802892/79833983-95db1d00-83ac-11ea-8e42-6115210372a3.png)
...and apply the template...
![grafik](https://user-images.githubusercontent.com/57802892/79834382-4812e480-83ad-11ea-84e2-8f88f07b37a5.png)
...the Browser "jumps" to the top of the page so scrolling is necessary to sent the ticket answer.

I checked this behavior in Firefox v75 64bit and Chrome v80 32bit and with redmine v4.0.5.stable and 4.1.1.stable.19704.

## Environment
Production:
Environment:
  Redmine version                4.0.5.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.5
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_checklists             3.1.16
  redmine_ckeditor               1.2.3
  redmine_contacts               4.3.0
  redmine_contacts_helpdesk      4.1.8
  redmine_issue_badge            0.1.3
  redmine_issue_templates        1.0.1
  redmine_lightbox2              0.5.1
  redmine_questions              1.0.2

Test:
Environment:
  Redmine version                4.1.1.stable.19704
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.5
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.5.3
  redmine_checklists             3.1.17
  redmine_ckeditor               1.2.3
  redmine_contacts               4.3.0
  redmine_contacts_helpdesk      4.1.8
  redmine_issue_badge            0.1.3
  redmine_issue_templates        1.0.1
  redmine_questions              1.0.2

## Expected Results
No "jumping" ;-)
## Actual Results
Page focus moves to top
## Workaround
nothing

Thank you very much!

**Comment by akiko-pusu** [comment]
@ChrisUHZ Hi, thanks for this inconvenient issue!
I've fixed on commit: aa63ecef

Could you please try the above?
I'm going to apply it to the develop branch. Then, ready to release the next version.

**Comment by ChrisUHZ** [comment]
@Akiko-Pusu It work´s perfect! Thank you very much!
Issue is fixed ;-)
