### ISSUE TITLE
Can't create/update Issue Templates

### ISSUE THREAD

**Issue by rroblik** [akiko-pusu/redmine_issue_templates#339]
Same as https://github.com/akiko-pusu/redmine_issue_templates/issues/323 but for **issue** template

Thanks

**Comment by akiko-pusu** [comment]
Please give me more detailed information.
Your version, and so on.

**Comment by rroblik** [comment]
Dear,

I’m using latest release. 

Please see related issue as it’s the same problem!

I can't specify the amount of charactes but if you just add some piece of lines (3-4) with less than ~100 characters there is no problem.
If I try to add longer template text, it can't be saved an an error page will be displayed.
e.g. a template text with 20 lines and 861 characters can't be saved.

**Comment by vividtone** [comment]
@rroblik, I recommend you to provide the following information. Maybe those are very helpful to the community people to investigate the issue.

* The exact version number of the plugin that you can see on Administration > Plugins page
* Screenshot of the create/update of a template form which is filled with the data that causes the error
* Content of production.log when the error occurred

**Comment by akiko-pusu** [comment]
@vividtone Really appreciate for your timely support!

@rroblik 
Thanks for your additional information.

As vividtone commented above, please give me more detailed information of your environment.

Exp. 

And it seems database column type does not accept the long text.
If you use my plugin version 1.0.0, please update to 1.0.1 and run migration task following README.

Here is the place to change the column type to accept long text.

https://github.com/akiko-pusu/redmine_issue_templates/commit/d79fdee037622ee2a9778227c808def5239a0c71

**Comment by rroblik** [comment]
Dear @akiko-pusu 

Here is my env information :

```
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.4.9-p362 (2019-10-02) [x86_64-linux-gnu]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.3
  Mercurial                      3.7.3
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.26.0
  Filesystem                     
Redmine plugins:
  common_mark                    0.3.1
  redmine_issue_templates        1.0.1
  redmine_omniauth_saml          0.9.9
```

**Comment by akiko-pusu** [comment]
@rroblik Thanks for your info.

In addition to this, could you see error messages from production.log?
It can be partial, so it would be very helpful if you could send me an error message.

You may see the error message like this: 

- "ActiveRecord::ValueTooLong (Mysql2::Error: ...."
- "Mysql2::Error: Data too long for column"

And if you don't mind, please check your table information of issue_templates, global_issue_templates.

```
show create table  issue_templates;
show create table global_issue_templates;
```

**Comment by rroblik** [comment]
@akiko-pusu ys for sur, here is the relevant `production.log` file 

```
ActiveRecord::ValueTooLong (Mysql2::Error: Data too long for column 'note' at row 1: INSERT INTO `issue_templates` (`title`, `project_id`, `tracker_id`, `author_id`, `note`, `description`, `created_on`, `updated_on`, `issue_title`, `related_link`, `link_title`) VALUES ('test', 43, 5, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sapien velit, aliquet eget commodo nec, auctor a sapien. Nam eu neque vulputate diam rhoncus faucibus. Curabitur quis varius libero. Lorem.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sapien velit, aliquet eget commodo nec, auctor a sapien. Nam eu neque vulputate diam rhoncus faucibus. Curabitur quis varius libero. Lorem.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sapien velit, aliquet eget commodo nec, auctor a sapien. Nam eu neque vulputate diam rhoncus faucibus. Curabitur quis varius libero. Lorem.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sapien velit, aliquet eget commodo nec, auctor a sapien. Nam eu neque vulputate diam rhoncus faucibus. Curabitur quis varius libero. Lorem.', 'retrete', '2020-04-30 10:05:52', '2020-04-30 10:05:52', '', '', '')):
```

**Comment by akiko-pusu** [comment]
OK, thank you so much!
Do you have a requirement to store long text for note (as a memo)?
I hardly imagine a use case to put a long sentence in a memo.

**Comment by rroblik** [comment]
Thanks,

Me need it to help end user to choose the good tracker by giving them more information about each tracker. Maybe it's a roundabout way using the plugin ...?

**Comment by akiko-pusu** [comment]
> Me need it to help end user to choose the good tracker by giving them more information about each tracker

It's not the main use case of my plugin.
In addition to this, the note field is not shown when the user creates a new issue.
The aim of the note field is to add some short comments for each template.

Example. The reason why created this issue templates and so on.

But I agree with your requirement.
I've request a related feature to Redmine's issue so many years ago ;-)
https://www.redmine.org/issues/442

**Comment by rroblik** [comment]
Hmmm ok... but #442 is marked as closed and fixed :(

**Comment by akiko-pusu** [comment]
@rroblik, Redmine 4.1.0 includes this feature. So you can try it!
https://www.redmine.org/versions/127

Here are sample screenshots.
I hope this would be of any help.

----

<img width="680" alt="tracker-setting" src="https://user-images.githubusercontent.com/122621/80706714-bda45080-8b23-11ea-9348-22fbfe8b704a.png">

----

<img width="759" alt="tracker-list" src="https://user-images.githubusercontent.com/122621/80706750-cbf26c80-8b23-11ea-937e-afff84989e7a.png">

----

<img width="607" alt="project-screen" src="https://user-images.githubusercontent.com/122621/80706836-f04e4900-8b23-11ea-8891-ea88d204877e.png">

----

<img width="877" alt="popup-issue" src="https://user-images.githubusercontent.com/122621/80706932-1d9af700-8b24-11ea-90aa-885f0f090e91.png">

**Comment by akiko-pusu** [comment]
@rroblik I close this issue.
Thanks for your reporting. Stay safe, wish you all the best.
