### ISSUE TITLE
Tracker change hides issue templates (Using qutebrowser)

### ISSUE THREAD

**Issue by einhander** [akiko-pusu/redmine_issue_templates#341]
## Summary
Tracker change hides issue templates

## Description
Then tracker is changed template UI is dissapears.
This only occurs on 1.0.1 version, 0.3.7 version is OK.
This problem not related to browser or redmine theme.

## Environment
Environment:
  Redmine version                4.0.4.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  redmine_gemavatar              1.1
  redmine_issue_templates        1.0.1
  redmine_issues_tree            0.0.14
  redmine_ldap_sync              2.2.0
  redmine_static_link            0.1.0

## Expected Results
Show relevant template if tracker changed.
## Actual Results
Template UI is disappeared.
## Workaround
Version 0.3.7 is OK

**Comment by akiko-pusu** [comment]
Hi, I could not reproduce this problem.
Are there any errors related to JavaScript or HTTP requests/responses on your browser?

<img width="532" alt="check-your-browser" src="https://user-images.githubusercontent.com/122621/81490463-9edd5100-92bd-11ea-80dd-1f5dadf482c1.png">

Please confirm:

- Check your browser's developer tool.
- Check all the templates what you want to use are marked as "Enabled"
- Check your Redmine's production logs.

**Comment by akiko-pusu** [comment]
@einhander Is your situation the same?

**Comment by einhander** [comment]
Oh, sorry, I'm on vacation now. I'll be at work in next week, so I can provide you a desired info.

**Comment by einhander** [comment]
It's seems that it's browser issue after all.
I use mainly qutebrowser, which is QtWebEngine based and I have that issue (see attached image). But it's works all right with old chrome 67. 
![123](https://user-images.githubusercontent.com/5439042/83657393-764d2c00-a5c9-11ea-9d31-c4c63d664712.png)

**Comment by akiko-pusu** [comment]
@einhander 
Thanks for your information! 

``qutebrowser, which is QtWebEngine based``

I'm going try to use this browser and confirm this situation.
But I'm not sure if I could fix the problem or not.

↑ Anyway, above is quite important and useful information. Thanks again!

If you don't mind, I hope to pin this issue. Like #310 (IE11)

I'd like to give the information to someone who has the same problem.

**Comment by einhander** [comment]
Here the additional info about qutebrowser:

```
qutebrowser v1.6.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.3
Qt: 5.11.3
PyQt: 5.11.3

sip: 4.19.14
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.27.2
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform: Linux-4.19.0-8-amd64-x86_64-with-debian-10.4, 64bit
Linux distribution: Debian GNU/Linux 10 (buster) (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

```

Thats really strange to me, because qutebrowser use chromium 65 as backend, and chrome 67 works.

**Comment by akiko-pusu** [comment]
Hi, @einhander 

I've tried to install ``qutebrowser`` in my MacOS.
I'm new for this browser, but it seems Issue Template (version1.0.3) works fine.
The template pulldown for the selected tracker is displayed.

Mine version is qutebrowser v1.13.0, and based on Chromium 80.0.3987.163.

Hope this would be any help.

```bash

$ /Applications/qutebrowser.app/Contents/MacOS/qutebrowser -V
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v1.13.0
Git commit: 74ba8f3dc-dirty on HEAD (2020-06-26 08:31:20 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.7.7
PyQt: 5.15.0

sip: 5.3.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: no
PyQt5.QtWebKitWidgets: no
pdf.js: 2.4.456 (bundled)
sqlite: 3.31.1
QtNetwork SSL: Secure Transport, macOS 10.15

Style: QMacStyle
Platform plugin: cocoa
OpenGL: Intel Inc., 2.1 INTEL-14.6.18
Platform: Darwin-19.5.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.15.5, x86_64


Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:00
```

**Comment by einhander** [comment]
Oh, sorry for the noice. I finaly figured out that hapend.
It seems that newer version or plugins was blocked by adblock mask based on server directoy sic! name.
Also I use the same setup on different machine, but with newer qutebrowser with same adblock, it works ok.
Don't know how it happend to block my redmine.
