### ISSUE TITLE
RSpec test failed

### ISSUE THREAD

**Issue by yui-har** [akiko-pusu/redmine_issue_templates#347]
## Summary
Testing the redmine_issue_templates plugin with Redmine(trunk) fails.

## Description
```spec
$ RAILS_ENV=test bundle exec rspec -I plugins/redmine_issue_templates/spec plugins/redmine_issue_templates/spec/
................................Capybara starting Puma...
* Version 4.3.5 , codename: Mysterious Traveller
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:51857
...F........................................................

Failures:

  1) Templates can be reorder via drag and drop Can drag and drop
     Failure/Error:
       expect do
         second_target.drag_to(last_target)
         sleep 0.5
       end.to change {
                IssueTemplate.order(:id).pluck(:position).to_a
              }.from([4, 1, 2, 3]).to([3, 1, 4, 2])

       expected `IssueTemplate.order(:id).pluck(:position).to_a` to have changed from [4, 1, 2, 3] to [3, 1, 4, 2], but did not change
     # ./plugins/redmine_issue_templates/spec/features/drag_and_drop_spec.rb:44:in `block (2 levels) in <top (required)>'
     # ~/.rbenv/shims/bundle:113:in `load'
     # ~/.rbenv/shims/bundle:113:in `<main>'

Finished in 51.38 seconds (files took 8.53 seconds to load)
92 examples, 1 failure

Failed examples:

rspec ./plugins/redmine_issue_templates/spec/features/drag_and_drop_spec.rb:26 # Templates can be reorder via drag and drop Can drag and drop

Coverage report generated for RSpec to ./coverage/redmine_issue_templates_spec. 4409 / 30757 LOC (14.33%) covered.
SimpleCov failed with exit 1
$
```

## Environment
- Redmine version
trunk([r19811](https://www.redmine.org/projects/redmine/repository/revisions/19811))
- Installed plugins
redmine_issue_templates(0.3-stable) Maybe version 1.0.x will also fail.
- Ruby version
2.5.8

## Workaround
The reason why the test fails is that we have upgraded jQuery UI from 1.11.0 to 1.12.1 with [Feature #31887: Update jQuery UI to 1.12.1](https://www.redmine.org/issues/31887) ([r19769](https://www.redmine.org/projects/redmine/repository/revisions/19769)).
Revert to r19768 and the test will succeed.

**Comment by akiko-pusu** [comment]
Oh! Thanks for the above reporting!

**Comment by akiko-pusu** [comment]
I've just confirmed this issue. Thanks again.
The test passed at the 4.1-stable branch and failed at the trunk.

**Comment by akiko-pusu** [comment]
I've just confirmed another problem with Redmine trunk.
Maybe I have to rewrite some JavaScript code.

**Comment by akiko-pusu** [comment]
@yui-har 
I think #348 is effective to the 0.3-stable branch and Redmine trunk, so I've just merged it.
But latest 1.x branch has another problem.

**Comment by yui-har** [comment]
@akiko-pusu 
> I think #348 is effective to the 0.3-stable branch and Redmine trunk, so I've just merged it.

I have confirmed the 0.3-stable branch. It's working properly.

```spec
$ RAILS_ENV=test bundle exec rspec -I plugins/redmine_issue_templates/spec plugins/redmine_issue_templates/spec/
................................Capybara starting Puma...
* Version 4.3.5 , codename: Mysterious Traveller
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:51169
............................................................

Finished in 56.42 seconds (files took 19.03 seconds to load)
92 examples, 0 failures

Coverage report generated for RSpec to ./coverage/redmine_issue_templates_spec. 4412 / 30841 LOC (14.31%) covered.
$
```

**Comment by akiko-pusu** [comment]
I've created another issue, so close this. Thanks for your support!
