### ISSUE TITLE
Allow non-administrator create issue templates

### ISSUE THREAD

**Issue by olegblecher** [akiko-pusu/redmine_issue_templates#355]
Hi, I'm running Redmine 4 on Ubuntu 20.04 (Ruby 2.6.5, Rails 5.2.4.2).

I'm only the admin here, not using Redmine so much myself. I'd like to allow a few non-admins the ability to create and edit templates. Can that be done somehow?

Thanks!

**Comment by akiko-pusu** [comment]
Hi, @olegblecher 
Thanks for the above question.

This plugin has two options:

1. Global issue templates
2. **Project scope** templates

1st, the **only administrator** can create ``Global issue template``.

2nd, assign some privileges and roles for your user. Then, the user can create/edit templates in the project scope.
You can also **apply a project scope template to a subproject** at the project template setting.

- Please see the Wiki:
  - https://github.com/akiko-pusu/redmine_issue_templates/wiki#enabled-issue-templates-as-project-module

I think the 2nd way meets your requirement. How about?

**Comment by olegblecher** [comment]
Yes, the 2nd one is perfect! 

Took me a while to find the settings where I allow issue Templates for a particular user type. If anyone finds this thread in the future: 

It's under Administration -> Roles and Permissions.

Thank you for your help!
