### ISSUE TITLE
checklistが追加できません(template_type is not defined エラー)

### ISSUE THREAD

**Issue by toku463ne** [akiko-pusu/redmine_issue_templates#364]
This is a template to report bug related to redmine issue templates plugin.
You can fill in any format, free style in case report features or questions.

## Summary
Issue templates / Add画面で”Checklist”を右にある「＋」ボタンで追加しようとしても反応しません

## Description
Chromeのデベロッパーツールを起動した状態で「＋」ボタンをクリックすると以下のエラーが出てました。
---
Uncaught ReferenceError: template_type is not defined
    at addCheckListItem (template_checklists.js?1595216048:39)
    at addCheckList (template_checklists.js?1595216048:21)
    at HTMLSpanElement.onclick (new:202)
  | addCheckListItem | @ | template_checklists.js?1595216048:39
-- | -- | -- | --
  | addCheckList | @ | template_checklists.js?1595216048:21
  | onclick | @ | new:202

## Environment

These informations are greatly helpful to support quickly.
You can get these informations from Redmine's information page.
(E.g. http://example.com/admin/info)

- Redmine version  
4.1.1.stable

- redmine_issue_template version
1.0.4

- Installed plugins  
  redmine_basix                  1.0.0
  redmine_checklists             3.1.16
  redmine_ckeditor               1.2.3
  redmine_code_review            1.0.0
  redmine_custom_js              0.1.0
  redmine_dashboard              2.7.1
  redmine_helpdesk               0.0.18
  redmine_issue_templates        1.0.4
  redmine_lightbox2              0.5.1
  redmine_revision_branches      0.3.2
  redmine_theme_changer          0.3.1
  redmineup_tags                 2.0.8
  sidebar_hide                   0.0.8

- Ruby version  
2.5.8-p224 (2020-03-31) [x86_64-linux]

- OS Platform  
Ubuntu server 20.04

- Database (MariaDB, MySQL, PostgreSQL) and its version  
MySQL 5.7.30

- Rails Env
5.2.4.2

## Visual Proof / Screenshot
![image](https://user-images.githubusercontent.com/11582761/87897698-1cc09400-ca87-11ea-9563-81fbab29e951.png)

## Expected Results  
”Checklist”を右にある「＋」ボタンでチェックリストが追加されること  

## Actual Results  
”Checklist”を右にある「＋」ボタンが反応しない。

## Workaround  
template_checklists.jsの37行目に let template_type =  'issue_template' を挿入したらとりあえず動きました。
  let template_type =  'issue_template'
  hidden.setAttribute('id', template_type + '_checklist')
  hidden.setAttribute('name', template_type + '[checklists][]')

Please let me know if you have any workaround.

**Comment by vividtone** [comment]
チェックリストプラグインは今後リリースされる Issue Template 1.0.5 と 0.3.9 から非対応になります。
詳しくは #363 をご確認ください。

**Comment by toku463ne** [comment]
承知しました。
早急にご回答いただきありがとうございます。

**Comment by akiko-pusu** [comment]
@toku463ne 
issueでのご連絡ありがとうございます！

また、ご不便おかけしております。
今後、無理に連携させている機能は不具合の発生に対応できなくなることが予想されます。
Workaroundのご提供も大変ありがたいですが、今回のように、ちょっとしたところで対応漏れが発生してしまうのが、その一例であります。

前田さんのコメントの通り、連携しているために本来の機能が使えなくなることは避けたいので、この方針を取らせていただきます。

@vividtone 前田さんもありがとうございます。

**Comment by toku463ne** [comment]
akiko-pusu さん
ご丁寧に説明いただき、ありがとうございます。
承知しました。
ちなみに Redmine checklist を購入しました。

**Comment by akiko-pusu** [comment]
ご協力感謝いたします。ありがとうございます！

**Comment by tiurlumbangaol** [comment]
Hi,

this is broken, because this commit : 
https://github.com/akiko-pusu/redmine_issue_templates/commit/2f25230664bcce39cf1a8829583d1acc0d10ecec

the previous commit, this issue was not there : 
https://github.com/akiko-pusu/redmine_issue_templates/commit/7808d41b7b5fc5f11e758f8be36d2f83aa07e710

**Comment by tiurlumbangaol** [comment]
solved in commit :
https://github.com/akiko-pusu/redmine_issue_templates/commit/add350bc886010198238c637fd205ed8619c4fb2

thank you so much @akiko-pusu :)
