### ISSUE TITLE
Redmine 3.3.0 - Internal error when trying to access new issues form from all issues list

### ISSUE THREAD

**Issue by jwciss** [akiko-pusu/redmine_issue_templates#40]
Since the Redmine update to 3.3.0 there is a new link to create an issue from the issue list view:

Projects -> View all issues -> New issue (direct link is /redmine/issues/new) instead of the previous way to create a new issue, accessible from inside a project, e.g. /redmine/projects/project1/issues/new

When using the issue templates plugin, this new link does not work:
![new_issue](https://cloud.githubusercontent.com/assets/18282521/16804326/7dfc3154-490b-11e6-9974-12e0e488caba.PNG)

Could you provide a fix for this error?

**Comment by akiko-pusu** [comment]
Oh! 😱 Thanks for your reporting above issue.
I'll comfirm this situation and try to fix it.

**Comment by jwciss** [comment]
I can confirm that the current master branch patch has solved this issue and also #41 , both on our local test environment and at your demo site (see test issues 239, 240). Thank you very much!

**Comment by akiko-pusu** [comment]
@jwciss,  I'm relieved to hear that.
And thank you so much for your reporting again, because this is a serious issue.
Please let us know if you have any requests or suggestions.
