### ISSUE TITLE
Redmine 3.3.0 - Cannot select template

### ISSUE THREAD

**Issue by jwciss** [akiko-pusu/redmine_issue_templates#41]
When navigating to the new issue form, very briefly one can see the template selection menu flashing, then disappears. Therefore no template can be selected. We're very much hoping for a quick fix at our company as we're using this template plugin a lot! Thanks

**Comment by akiko-pusu** [comment]
@jwciss 
Thanks for reporting issue and using this plugin.
Could you please give me more details?

**Comment by jwciss** [comment]
The Plugin is correctly confirmed in our test environment and should show the template selection menu as usual, but it's not there. After clicking "new issue", you can see the template dropbox menu flashing very briefly, then it looks like this: ![no_template](https://cloud.githubusercontent.com/assets/18282521/16866078/d4e18a64-4a69-11e6-9569-0d5fdb0f5412.PNG)

However, the menu is there in the html code:

```
<div id="template_area">
  <p>
    <label for="issue_template">Issue template</label>
    <select id="issue_template" name="issue_template">
      <option value="">---</option>
    </select>

    <a class="icon template_tooltip" id="link_template_dialog">
      Filter Templates
    </a>

    <a class="icon icon-erase" href="#" title="Clear subject and description text."
       onclick="eraseSubjectAndDescription();">
      Clear subject and description text.
    </a>
    <span id="template_status-area"></span>
  </p>
  <div class="template_help box" id="template_help_content" style="display: none;">
    
    <div id="template_help_hide">
      <a href="#" onClick="checkExpand('template_help_content');" title="Close help message.">[x]</a>
    </div>
  </div>

  <!-- dialog box -->
  <div id="issue_template_dialog" style="overflow:visible; display: none;">
    <label for="template_search_filter">
      Filter Templates
    </label>
    <input type="text" name="template_search_filter"
           id="template_search_filter" class="autocomplete">
    <div id="filtered_templates_list"></div>
  </div>
  <!-- dialog box -->

</div>
```


Full code:
[no_template_html.txt](https://github.com/akiko-pusu/redmine_issue_templates/files/365352/no_template_html.txt)

**Comment by akiko-pusu** [comment]
Thanks for additional information!
But I’m sorry I could not reproduce this situation....

If you don’t mind, please give me some more information, such as environment info or installed plugin info. (It’s displayed at http://YOUR_REDMINE_URL/admin/info .)

And I’ve applied workaround for #40. Could you please try latest master branch?
Also you can confirm plugin’s behavior on my demo site.
http://redmine-akiko.ruby.iijgio.com/projects/sample-project/wiki
(You can login with demo admin account.)
