### ISSUE TITLE
Template is loaded after the error when required fields are not filled. 

### ISSUE THREAD

**Issue by cou2jpn** [akiko-pusu/redmine_issue_templates#50]
いつもご対応いただき、ありがとうございます。

必須フィールドが未入力でチケットを登録しようとした時のエラーで、テンプレートがロードされてしまいます。
プラグインの設定で「Replace subject and description」をONにしていると、テンプレートのロードにより記載内容が消えてしまい、ユーザビリティが良くありません。
この場合はロードしないよう、修正できないでしょうか？

Environment

- redmine: 3.3.0
- redmine_issue_templates: 0.1.2

**Comment by akiko-pusu** [comment]
こちらこそ、ご要望・ご報告ありがとうございます！
状況を確認して対応を進めます。引き続きどうぞよろしくお願いいたします。

**Comment by akiko-pusu** [comment]
引き続きありがとうございます。
テンプレートは、デフォルトテンプレートの場合でしょうか？
必須フィールドがある際は、Redmine 本体側の機能として、送信ボタンが押せない、という挙動のほうが望ましい気はしますね。
本体側にissueやパッチが出ていないか、view customizeプラグインあたりでなんとか出来ないかも探してみます。

**Comment by cou2jpn** [comment]
ご検討いただきありがとうございます。

デフォルトではないテンプレートで、チケットを作成しようとしていた場合であっても、
必須項目チェックにひっかかると、デフォルトのテンプレートがロードされる挙動となっております。

エラーメッセージが表示させるために、チケット登録画面がリロードされるので、
このトリガーをテンプレートのロードで除外できればよいのかな？と思いました。
（ただ、Redmine本体側で仕掛けが必要となりそうですが。）

引き続きよろしくお願いします。

**Comment by akiko-pusu** [comment]
> デフォルトではないテンプレートで、チケットを作成しようとしていた場合であっても、
必須項目チェックにひっかかると、デフォルトのテンプレートがロードされる挙動となっております。

画面的に再読み込みになりますからね....。

> エラーメッセージを表示させるために、チケット登録画面がリロードされるので、このトリガーをテンプレートのロードで除外できればよいのかな？
 どちらにしても、画面再読み込みによってテンプレートのプルダウン部分も再度生成 -> トラッカーにデフォルト値が設定されていればそのテンプレを読み込む挙動になってしまいます。

一番望ましいのは、入力する方（オペレーターさんなど）が、必須項目の入力をミスしないこと、抜けている場合は送信ボタンが押せないとか、必須項目が抜けているといったメッセージを送信前に受け取ることかなと思っています。
ですので、Redmine本体側になにか働きかけしたいなあと思います。

**Comment by akiko-pusu** [comment]
@cou2jpn 遅くなってしまって申し訳ございません！
Redmine本体に手を加えることは避けたいのと、なるべく簡単に済ませる方法で...と思いまして、JavaScriptのみの修正で対応してみました。
masterにはマージしていませんが、リラクタリングの箇所をふくめて、近々バージョンを上げる予定です。

もしお急ぎでしたら、 commit: 4e0ebc7 の変更をJavaScriptに適用してみてください。
対応方法としましては、こんな感じです。

- 必須フィールドも含め、チケット作成時にエラーメッセージ付きでレスポンスが返ってきた場合
 -  エラーのFlash message の要素がHTML中に含まれていたら、Templateの上書きを行わない

どうぞよろしくお願いいたします！
本件、closedにさせていただいてもよろしいでしょうか？

**Comment by akiko-pusu** [comment]
遅くなりましたが、こちらの件、v0.1.3のリリースに含めております。
もしまた何かありましたら、再度ご報告いただけると幸いです。

**Comment by cou2jpn** [comment]
修正いただき、どうもありがとうございました！
良好に動作しております。
また、確認が大変遅くなってすみませんでした。
