### ISSUE TITLE
cannot load issue template

### ISSUE THREAD

**Issue by archonwang** [akiko-pusu/redmine_issue_templates#60]
@akiko-pusu , when create new  issue, cannot load issue template.

error log
> A NameError occurred in issue_templates#load:
>  
>   undefined local variable or method `checklist_json' for #<GlobalIssueTemplate:0x007fb8b079d108>
>   plugins/redmine_issue_templates/app/models/global_issue_template.rb:35:in `checklist'
>  
>  
> -------------------------------
> Request:
> -------------------------------
>  
> * URL : http://192.168.1.41/projects/10/issue_templates/load?is_triggered_by_status=false
>   * HTTP Method: POST
>   * IP address : 192.168.60.238
>   * Parameters : {"issue_template"=>"1", "template_type"=>"global", "is_triggered_by_status"=>"false", "controller"=>"issue_templates", "project_id"=>"10", "action"=>"load"}
>   * Timestamp  : 2016-09-05 02:59:41 UTC
>   * Server : jira
>   * Rails root : /opt/redmine-3.3
>   * Process: 28571
>  
> -------------------------------
> Session:
> -------------------------------
>  
>   * session id: "6d78f6e25bf633349961315313f7b92f"
>   * data: {"session_id"=>"6d78f6e25bf633349961315313f7b92f",
>    "user_id"=>8,
>    "tk"=>"f57f69f7419af208a5fe484464a73688ee6c3cf4",
>    "sudo_timestamp"=>1473041388,
>    "_csrf_token"=>"eNZEynNjtNO5Vo81cg6tPF0jgigzpUZsezkP1rrhbVQ=",
>    "recent_projects"=>[10, 2],
>    "query"=>
>     {:project_id=>2,
>      :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}},
>      :group_by=>nil,
>      :column_names=>nil,
>      :totalable_names=>[:estimated_hours, :spent_hours]},
>    "issues_index_sort"=>"id:desc"}
>  
> -------------------------------
> Environment:
> -------------------------------
>  
>   * CONTENT_LENGTH                                 : 37
>   * CONTENT_TYPE                                   : application/x-www-form-urlencoded; charset=UTF-8
>   * GATEWAY_INTERFACE                              : CGI/1.2
>   * HTTP_ACCEPT                                    : */*
>   * HTTP_ACCEPT_ENCODING                           : gzip, deflate
>   * HTTP_ACCEPT_LANGUAGE                           : zh-CN,zh;q=0.8,en;q=0.6
>   * HTTP_CONNECTION                                : keep-alive
>   * HTTP_COOKIE                                    : autologin=df95bc5acf08ba7db8767eb2c92997aaf2089912; _redmine_session=R3Fuc09MWGUzTDVTNFA2MnBxcml4Tk9ZNHhMNXIxRmtEb3ZkaU1jb0I5b2ttazM5ODU3OFdKS1RFOFdMY1QzaTBOUGl4SkZianVTb1RwMEFZUmlkdDBWVTZDTS9iTGtQcDMxb1Z6amQ1d3B6TmlDWEV5M1NCL0Y4aGlUTnZCRkp5V2tKK1dmTVhaYzFIc1EvZThRQXhReFZ1bVRFdVZWZ2I2U0xIVFhHSUdvMThNUGxTdCtpYmxNMHk3eUt4SDRrWHRqNkpDL2h5OWdiSFMyaDAwK0pzWWh4MXlEYnAyb1Fqb0ZPeURqejRFVnNUMW9uajVlK3ptMjk1T25TUEtGNzFvWmZoQ3dKU3lpVWJvWlJwUUE4Zkpqbm04U0x1YURIK2VZTzRWR3VnRVNKSDhpd3JQSG0zc1Q0cm5waGJRTHc3ZUxwZTJGL0RnY1VGaFhvQU02M2NjZ2svYU1WMitib01mYUpjajNEV1M0bHpGK3I0b3crR2UzZUNKRUNSNUNwL001NHJsUVQzb0VuVXlxdU9xOElaYWU3VnpIY2k5WVUwa0JyM2NxTVJiVEw5YzhSSFNpK3YzcHFBQWNHcjFJQ2doL3dYbmIxbEVNb0NkWkp6WEN4MDlTcmNRRFUxNnk2M0lDbVN6TmFsMFdjQzFPWXp4VmFtRXZDekU3THZ4QktOZkdCNThrbStmTlZRRG9IQkRHd3pyY3NuZUtBWHVUQndoUy9ZcFBlMnNkbTFZamJNNGVVQTdSWjBkUnpOakdBVzR2RjMxU3JYRXI1b3NvRG1rWjV3NkpHUldjdk9DRWFPT0JOazBIRFdhQT0tLWJsdjNhWmloNi9mNGwvQXJmWkpTYkE9PQ%3D%3D--f5332117e89c078fdbc9762dfb78111e1199cad1
>   * HTTP_HOST                                      : 192.168.1.41
> * HTTP_ORIGIN : http://192.168.1.41
> * HTTP_REFERER : http://192.168.1.41/projects/win/issues/new
>   * HTTP_USER_AGENT                                : Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36
>   * HTTP_VERSION                                   : HTTP/1.1
>   * HTTP_X_CSRF_TOKEN                              : leHBqak/1ei91D5iKCasSlgCZy+D/0c8ia46LSnmBuntN4Vj2lxhOwSCsVdaKAF2BSHlB7BaAVDylzX7kwdrvQ==
>   * HTTP_X_REQUESTED_WITH                          : XMLHttpRequest
>   * ORIGINAL_FULLPATH                              : /projects/10/issue_templates/load?is_triggered_by_status=false
>   * ORIGINAL_SCRIPT_NAME                           :
>   * PATH_INFO                                      : /projects/10/issue_templates/load
>   * QUERY_STRING                                   : is_triggered_by_status=false
>   * REMOTE_ADDR                                    : 192.168.60.238
>   * REQUEST_METHOD                                 : POST
>   * REQUEST_PATH                                   : /projects/10/issue_templates/load
>   * REQUEST_URI                                    : /projects/10/issue_templates/load?is_triggered_by_status=false
>   * ROUTES_49344860_SCRIPT_NAME                    :
>   * SCRIPT_NAME                                    :
>   * SERVER_NAME                                    : 192.168.1.41
>   * SERVER_PORT                                    : 80
>   * SERVER_PROTOCOL                                : HTTP/1.1
>   * SERVER_SOFTWARE                                : thin 1.7.0 codename Dunder Mifflin
>   * action_controller.instance                     : #<IssueTemplatesController:0x007fb8b08d8608>
>   * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x000000057ed6a0>
>   * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007fb8b08afcd0>
>   * action_dispatch.cookies_digest                 :
>   * action_dispatch.cookies_serializer             :
>   * action_dispatch.encrypted_cookie_salt          : encrypted cookie
>   * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
>   * action_dispatch.http_auth_salt                 : http authentication
>   * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x000000044ec510>
>   * action_dispatch.logger                         : #<ActiveSupport::Logger:0x00000005c63478>
>   * action_dispatch.parameter_filter               : [:password]
>   * action_dispatch.redirect_filter                : []
>   * action_dispatch.remote_ip                      : 192.168.60.238
>   * action_dispatch.request.accepts                : [#<Mime::Type:0x007fb8b08d2708 @synonyms=[], @symbol=nil, @string="*/*", @hash=4103649980317762547>]
>   * action_dispatch.request.content_type           : application/x-www-form-urlencoded
>   * action_dispatch.request.formats                : [#<Mime::Type:0x007fb8b08d2708 @synonyms=[], @symbol=nil, @string="*/*", @hash=4103649980317762547>]
>   * action_dispatch.request.parameters             : {"issue_template"=>"1", "template_type"=>"global", "is_triggered_by_status"=>"false", "controller"=>"issue_templates", "project_id"=>"10", "action"=>"load"}
>   * action_dispatch.request.path_parameters        : {:controller=>"issue_templates", :project_id=>"10", :action=>"load"}
>   * action_dispatch.request.query_parameters       : {"is_triggered_by_status"=>"false"}
>   * action_dispatch.request.request_parameters     : {"issue_template"=>"1", "template_type"=>"global"}
>   * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"6d78f6e25bf633349961315313f7b92f", "user_id"=>8, "tk"=>"f57f69f7419af208a5fe484464a73688ee6c3cf4", "sudo_timestamp"=>1473041388, "_csrf_token"=>"eNZEynNjtNO5Vo81cg6tPF0jgigzpUZsezkP1rrhbVQ=", "recent_projects"=>[10, 2], "query"=>{:project_id=>2, :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}}, :group_by=>nil, :column_names=>nil, :totalable_names=>[:estimated_hours, :spent_hours]}, "issues_index_sort"=>"id:desc"}
>   * action_dispatch.request_id                     : 43cba62d-f407-4426-876f-ea788028da9f
>   * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x00000005e1e2b8>
>   * action_dispatch.secret_key_base                : 59dda17a42803617f96151518b9aeecb94e132c6f140123f1982e1c8ae15d0103ffa854c4d8b0019
>   * action_dispatch.secret_token                   :
>   * action_dispatch.show_detailed_exceptions       : false
>   * action_dispatch.show_exceptions                : true
>   * action_dispatch.signed_cookie_salt             : signed cookie
>   * async.callback                                 : #<Method: Thin::Connection#post_process>
>   * async.close                                    : #<EventMachine::DefaultDeferrable:0x007fb8b08df1d8>
>   * rack.errors                                    : #<IO:0x0000000143d590>
>   * rack.input                                     : #<StringIO:0x007fb8b08dfe08>
>   * rack.multiprocess                              : false
>   * rack.multithread                               : true
>   * rack.request.cookie_hash                       : {"autologin"=>"df95bc5acf08ba7db8767eb2c92997aaf2089912", "_redmine_session"=>"R3Fuc09MWGUzTDVTNFA2MnBxcml4Tk9ZNHhMNXIxRmtEb3ZkaU1jb0I5b2ttazM5ODU3OFdKS1RFOFdMY1QzaTBOUGl4SkZianVTb1RwMEFZUmlkdDBWVTZDTS9iTGtQcDMxb1Z6amQ1d3B6TmlDWEV5M1NCL0Y4aGlUTnZCRkp5V2tKK1dmTVhaYzFIc1EvZThRQXhReFZ1bVRFdVZWZ2I2U0xIVFhHSUdvMThNUGxTdCtpYmxNMHk3eUt4SDRrWHRqNkpDL2h5OWdiSFMyaDAwK0pzWWh4MXlEYnAyb1Fqb0ZPeURqejRFVnNUMW9uajVlK3ptMjk1T25TUEtGNzFvWmZoQ3dKU3lpVWJvWlJwUUE4Zkpqbm04U0x1YURIK2VZTzRWR3VnRVNKSDhpd3JQSG0zc1Q0cm5waGJRTHc3ZUxwZTJGL0RnY1VGaFhvQU02M2NjZ2svYU1WMitib01mYUpjajNEV1M0bHpGK3I0b3crR2UzZUNKRUNSNUNwL001NHJsUVQzb0VuVXlxdU9xOElaYWU3VnpIY2k5WVUwa0JyM2NxTVJiVEw5YzhSSFNpK3YzcHFBQWNHcjFJQ2doL3dYbmIxbEVNb0NkWkp6WEN4MDlTcmNRRFUxNnk2M0lDbVN6TmFsMFdjQzFPWXp4VmFtRXZDekU3THZ4QktOZkdCNThrbStmTlZRRG9IQkRHd3pyY3NuZUtBWHVUQndoUy9ZcFBlMnNkbTFZamJNNGVVQTdSWjBkUnpOakdBVzR2RjMxU3JYRXI1b3NvRG1rWjV3NkpHUldjdk9DRWFPT0JOazBIRFdhQT0tLWJsdjNhWmloNi9mNGwvQXJmWkpTYkE9PQ==--f5332117e89c078fdbc9762dfb78111e1199cad1"}
>   * rack.request.cookie_string                     : autologin=df95bc5acf08ba7db8767eb2c92997aaf2089912; _redmine_session=R3Fuc09MWGUzTDVTNFA2MnBxcml4Tk9ZNHhMNXIxRmtEb3ZkaU1jb0I5b2ttazM5ODU3OFdKS1RFOFdMY1QzaTBOUGl4SkZianVTb1RwMEFZUmlkdDBWVTZDTS9iTGtQcDMxb1Z6amQ1d3B6TmlDWEV5M1NCL0Y4aGlUTnZCRkp5V2tKK1dmTVhaYzFIc1EvZThRQXhReFZ1bVRFdVZWZ2I2U0xIVFhHSUdvMThNUGxTdCtpYmxNMHk3eUt4SDRrWHRqNkpDL2h5OWdiSFMyaDAwK0pzWWh4MXlEYnAyb1Fqb0ZPeURqejRFVnNUMW9uajVlK3ptMjk1T25TUEtGNzFvWmZoQ3dKU3lpVWJvWlJwUUE4Zkpqbm04U0x1YURIK2VZTzRWR3VnRVNKSDhpd3JQSG0zc1Q0cm5waGJRTHc3ZUxwZTJGL0RnY1VGaFhvQU02M2NjZ2svYU1WMitib01mYUpjajNEV1M0bHpGK3I0b3crR2UzZUNKRUNSNUNwL001NHJsUVQzb0VuVXlxdU9xOElaYWU3VnpIY2k5WVUwa0JyM2NxTVJiVEw5YzhSSFNpK3YzcHFBQWNHcjFJQ2doL3dYbmIxbEVNb0NkWkp6WEN4MDlTcmNRRFUxNnk2M0lDbVN6TmFsMFdjQzFPWXp4VmFtRXZDekU3THZ4QktOZkdCNThrbStmTlZRRG9IQkRHd3pyY3NuZUtBWHVUQndoUy9ZcFBlMnNkbTFZamJNNGVVQTdSWjBkUnpOakdBVzR2RjMxU3JYRXI1b3NvRG1rWjV3NkpHUldjdk9DRWFPT0JOazBIRFdhQT0tLWJsdjNhWmloNi9mNGwvQXJmWkpTYkE9PQ%3D%3D--f5332117e89c078fdbc9762dfb78111e1199cad1
>   * rack.request.form_hash                         : {"issue_template"=>"1", "template_type"=>"global"}
>   * rack.request.form_input                        : #<StringIO:0x007fb8b08dfe08>
>   * rack.request.form_vars                         : [FILTERED]
>   * rack.request.query_hash                        : {"is_triggered_by_status"=>"false"}
>   * rack.request.query_string                      : is_triggered_by_status=false
>   * rack.run_once                                  : false
>   * rack.session                                   : #<ActionDispatch::Request::Session:0x007fb8b08dc258>
>   * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x007fb8b08dc168>
>   * rack.url_scheme                                : http
>   * rack.version                                   : [1, 0]
>  
> -------------------------------
> Backtrace:
> -------------------------------
>  
>   plugins/redmine_issue_templates/app/models/global_issue_template.rb:35:in `checklist'
>   plugins/redmine_issue_templates/app/models/global_issue_template.rb:41:in `template_json'
>   plugins/redmine_issue_templates/app/controllers/issue_templates_controller.rb:114:in `load'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by akiko-pusu** [comment]
Hi, could you tell me the version you use? (v0.1.2 or v0.1.3?)
If v0.1.3, migration is required.

**Comment by archonwang** [comment]
I used 0.1.3. in redmine 3.3.X
oh, maybe I have missed some steps. I will test it later. thanks

**Comment by archonwang** [comment]
@akiko-pusu ， Checked it and it worked well. 
Thanks.

**Comment by akiko-pusu** [comment]
@archonwang You are welcome, always thanks for your support!
