### ISSUE TITLE
Global Issue Template?

### ISSUE THREAD

**Issue by scharc** [akiko-pusu/redmine_issue_templates#61]
Is there a way to add a template in the root project and enable it automaticly for all child-projects? Like a global issue template?

We are using redmine to track over 6000 artworks in a museum and every new exibition will add another 2000 sub-projects... I will go crazy if I have to manually enable "inherite from parent" option

**Comment by akiko-pusu** [comment]
Hi, @scharc, thank you so much for using my plugin, and I'm so sorry for the delayed response....
It's understandable that setting "inherite from parent” option to many projects task is so heavy.

This is just an idea, that I ‘m planning to providing feature to bulk update "inherite from parent” option of inherit projects via rake task. 
(Of course, it’s not so difficult to enabled the same feature from web interface.)

But I’m wonder how much do this feature impact performance....
Are your projects deeply-nested or not? I hope nested is not so deep.

I would like to get your feedback!
Also, I’m going to make a prototype with feature branch soon.

BTW, sorry., for my English is terrible.

**Comment by akiko-pusu** [comment]
Hi, @scharc 
I’ve made instance method and rake task to apply/unapply inherit templates for all the hild projects.
Above has not merged into master yet, develop branch only.

You can use this feature from rake task.
To confirm rake tasks related to redmine_issue_templates, please run “rake -T” or “bundle exec rake -T”, and you can find these tasks.

```
rake redmine_issue_templates:apply_inhelit_template_to_child_projects[project_id]      # Apply inhelit template setting to child projects
rake redmine_issue_templates:default                                                   # Run test for redmine_issue_template plugin
rake redmine_issue_templates:spec                                                      # Run spec for redmine_issue_template plugin
rake redmine_issue_templates:test                                                      # Run tests
rake redmine_issue_templates:unapply_inhelit_template_from_child_projects[project_id]  # Unapply inhelit template setting from child projects
rake redmine_issue_templates:yardoc    
```

If you want to apply inherit templates setting all the child project of project_id: 1 (as parent project), please run rake command like this:

```
rake redmine_issue_templates:apply_inhelit_template_to_child_projects[1]   
``` 

Of course, enable to run the same feature from Redmine’s web interface is not so difficult, but I’m afraid how long convert completes, like your situation that parent project has 2000 sub-projects....

Anyway, I’m going to merge this feature to master branch soon.

**Comment by nunohorta** [comment]
Hi @akiko-pusu , thanks for this plugin! Do you have any plans on including this feature on a next release? At the moment I would like to have a Global template set as default for every project where this plugin is enabled. Unless it's overrided on the project itself :)

**Comment by akiko-pusu** [comment]
@nunohorta 
Thanks for your feedback. Rake task to apply/unapply inherit templates for all the child projects, is now included version 0.1.4.
But now this bulk update feature can't submitted from Web UI.

Does this feature meet your request if web ui is implemented?
Or do you hope global template can be default template?

**Comment by nunohorta** [comment]
@akiko-pusu thanks for getting back to this issue. Inheritance from a global template could be a good solution if done through the Web UI :) 

Ideally setting a global template as default for every project would be perfect. This way you don't need to go to every single project and inherit from a global template. In my case, I have around 40 projects on redmine, so you can see how long that could take :)

**Comment by akiko-pusu** [comment]
related: #90

**Comment by akiko-pusu** [comment]
Hi, I’m going to release v0.1.5, to implement some feature related for this request.

Pre release: 
* https://github.com/akiko-pusu/redmine_issue_templates/releases/tag/v0.1.5

I’m not sure if the release meets your request enough, but please feel free to feedback!

**Comment by nunohorta** [comment]
thanks @akiko-pusu . Does this update affects any existing templates?

**Comment by akiko-pusu** [comment]
@nunohorta 

I’ve reviewed the implementation about Global issue templates of this time, since I received some reports that "it is very difficult to associate global templates to each project in case so many projects exist.”

However, in order to maintain compatibility with previous version's behavior, it applies only when the "apply global template to all projects" option is set at plugin settings screen.

Even if this option is enabled, if some templates are defined for each project, global templates are not loaded. If this option is not activated, the behavior is the same to version 0.1.4 or before.
Global templates are only applied to projects that associated with projects on  template setting screen.
