### ISSUE TITLE
Using template in reply

### ISSUE THREAD

**Issue by pastukhov** [akiko-pusu/redmine_issue_templates#67]
Hi!
Is it possible to use templates in reply to issue?

**Comment by akiko-pusu** [comment]
@pastukhov Thanks for your request.
I also hope to implement this feature, so please vote / cheer for me :) Proberbry it’s not so difficult rather than issue description’s template.

**Comment by plindema** [comment]
For which milestone is this feature planned now, please?

**Comment by Niremizov** [comment]
+1

**Comment by Niremizov** [comment]
Use https://github.com/commandprompt/redmine_canned_responses

**Comment by akiko-pusu** [comment]
I've released this feature on v0.3.1.
But sorry this version supports only for Redmine4.x.
