### ISSUE TITLE
After I update this, database migration was not working.

### ISSUE THREAD

**Issue by xyz37** [akiko-pusu/redmine_issue_templates#82]
Then I cretae table script add

> CREATE TABLE IF NOT EXISTS `global_issue_templates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `issue_title` varchar(255) DEFAULT NULL,
  `tracker_id` int(11) DEFAULT NULL,
  `author_id` int(11) DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  `description` text,
  `enabled` tinyint(1) NOT NULL DEFAULT '0',
  `position` int(11) DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `checklist_json` text,
  PRIMARY KEY (`id`),
  KEY `index_global_issue_templates_on_author_id` (`author_id`),
  KEY `index_global_issue_templates_on_tracker_id` (`tracker_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

> CREATE TABLE IF NOT EXISTS `global_issue_templates_projects` (
  `project_id` int(11) DEFAULT NULL,
  `global_issue_template_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

> CREATE TABLE IF NOT EXISTS `issue_templates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `issue_title` varchar(255) DEFAULT NULL,
  `project_id` int(11) NOT NULL,
  `tracker_id` int(11) DEFAULT NULL,
  `author_id` int(11) DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  `description` text,
  `enabled` tinyint(1) NOT NULL DEFAULT '0',
  `is_default` tinyint(1) NOT NULL DEFAULT '0',
  `enabled_sharing` tinyint(1) NOT NULL DEFAULT '0',
  `position` int(11) NOT NULL DEFAULT '1',
  `created_on` datetime DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `checklist_json` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

> CREATE TABLE IF NOT EXISTS `issue_template_settings` (
  `project_id` int(11) DEFAULT NULL,
  `help_message` text,
  `enabled` tinyint(1) NOT NULL DEFAULT '0',
  `should_replaced` tinyint(1) DEFAULT '0',
  `inherit_templates` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by akiko-pusu** [comment]
Hi, @xyz37 
Thank you so much for your feedback and sorry to bother you...
Could you please let me know the version of Redmine and this plugin.
And please tell me if you tried only to update plugin or both Redmine and plugin?

**Comment by xyz37** [comment]
Thanks for your replay.
Issue template 0.1.4 and Redmine info below.

Environment:
  Redmine version                3.3.0.stable
  Ruby version                   2.3.0-p0 (2015-12-25) [i386-mingw32]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.4
  Git                            2.9.0
  Filesystem                     
Redmine plugins:
  advanced_roadmap_v2            2.4.3
  author                         0.1.0
  clipboard_image_paste          1.10
  contact_form                   0.1.2
  download                       0.1.1
  easy_gantt                     1.7
  extended_fields                0.2.4
  extended_profile               1.2.1
  like                           1.0.0
  meta                           0.2.3
  redmine_add_top_menus          0.0.1
  redmine_agile                  1.4.2
  redmine_banner                 0.1.1
  redmine_checklists             3.1.3
  redmine_ckeditor               1.1.4
  redmine_code_review            0.7.0
  redmine_information            1.0.2
  redmine_issue_templates        0.1.4
  redmine_lightbox2              0.3.2
  redmine_my_page                0.1.9
  redmine_per_project_formatting 0.0.4
  redmine_pull_requests          0.3
  redmine_query_share            2.0.1
  redmine_theme_changer          0.2.0
  redmine_watcher_groups         0.0.3git
  redmine_wiki_extensions        0.7.0
  redmine_wiki_lists             0.0.6
  scrum                          0.16.2
  scrum2b                        2.0

**Comment by akiko-pusu** [comment]
Could you please run this sql command on your target database?

```
select * from schema_migrations where version like '%redmine_issue_templates%';
```

If migration does not have any problem, the result will be as following.

```
1-redmine_issue_templates
2-redmine_issue_templates
3-redmine_issue_templates
4-redmine_issue_templates
2014020191500-redmine_issue_templates
20121208150810-redmine_issue_templates
20130630141710-redmine_issue_templates
20130701024625-redmine_issue_templates
20140307024626-redmine_issue_templates
20140312054531-redmine_issue_templates
20140330155030-redmine_issue_templates
20160727222420-redmine_issue_templates
20160828190000-redmine_issue_templates
20160829001500-redmine_issue_templates
20160829001530-redmine_issue_templates
20170317082100-redmine_issue_templates
```

And global issue template should be created with using this migration file.
https://github.com/akiko-pusu/redmine_issue_templates/blob/master/db/migrate/20140307024626_create_global_issue_templates.rb (This file was added at version 0.1.2)

I wonder why migration does not work fine, but it may be caused some wrong schema migration records exist.
Also is the previous version of issue template that you use the one cloned from my repository, or folked one?

**Comment by xyz37** [comment]
Above query results were below.

> "version"
"1-redmine_issue_templates"
"2-redmine_issue_templates"
"3-redmine_issue_templates"
"4-redmine_issue_templates"
"2014020191500-redmine_issue_templates"
"20121208150810-redmine_issue_templates"
"20130630141710-redmine_issue_templates"
"20130701024625-redmine_issue_templates"
"20140307024626-redmine_issue_templates"
"20140312054531-redmine_issue_templates"
"20140330155030-redmine_issue_templates"
"20160727222420-redmine_issue_templates"
"20160828190000-redmine_issue_templates"
"20160829001500-redmine_issue_templates"
"20160829001530-redmine_issue_templates"

**Comment by akiko-pusu** [comment]
@xyz37 Thanks for additional information.
And could you please tell me which version you used just before update?

In case migration program works fine, tables are created and version of migration are recorded into schema_migrations table.

Let me confirm have you dropped tables related to issue templates?
And if you does not create any template record yet, and hope to uninstall and re-install this plugin, please see README.

1. Unistall:
rake db:migrate_plugins NAME=redmine_issue_templates VERSION=0 RAILS_ENV=production
(After that, records of migration are removed from schema_migrations table)

2. re-install
rake db:migrate_plugins NAME=redmine_issue_templates RAILS_ENV=production

**Comment by akiko-pusu** [comment]
How does your situation go?
Since there is no reply, I will close it. Please open new issue if you have some trouble.
