### ISSUE TITLE
チケットテンプレート作成時、日本語が入力できない

### ISSUE THREAD

**Issue by Manabu-H** [akiko-pusu/redmine_issue_templates#86]
もとはBitBucketへの投稿でしたが、こちらに再掲します。

---

こんにちは。

チケットテンプレート作成時、日本語で項目を埋めて「作成」を押下するとInternal　Errorに なります。ログを確認するとMysqlのエラーでIncorrect String Valueと出ています。

試に英文字だけでテンプレートを作成すると特にエラーは発生しません。

RedmineのVersionは3.3.0stableで、プラグインのVersionは0.1.1です。

何かわかることがあればコメントいただけると助かります。 よろしくお願いします。

---

Akiko.T リポジトリの所有者 

こんにちは、こちらへのメッセージありがとうございます！ 大変申しわけないのですが、現在マスターになるリポジトリをBitbucketからGitHubに移行しております。

日本語でかまいませんので、もしよろしければ、 https://github.com/akiko-pusu/redmine_issue_templates 側からダウンロードをお願いします。

最新版は v0.1.4 になりますが、こちらは間も無くバグフィックスのリリースをする予定です。 おそらく v0.1.3なら問題ないと思います。

https://github.com/akiko-pusu/redmine_issue_templates/releases

また、可能でしたらissueもGitHub側に寄せていただけると助かります。 ただ、アカウントをご用意いただくのが申し訳ないので、こちらでお受けするのでもいいのですが、ソースコードの最新はGitHub側になるので、回避策の提示などがちょっとやりにくいかもしれません。

**Comment by akiko-pusu** [comment]
@Manabu-H さん。
ご迷惑おかけして申し訳ございません。
幾つか質問をさせていただきます。

1. Redmineの環境はどのような状態でしょうか？
Redmine3.3のクリーンインストールでしょうか？
もしくは RedmineとIssue Template Pluginどちらもバージョンアップしながら継続して利用されている状況でしょうか。

2. テンプレートを使わずに新規でチケットを作成することは可能でしょうか？
また、この場合に、テンプレートに登録しようとしたのと同じ内容をチケットに入力して作成することは可能でしょうか？

3. MySQLのデータベース、テーブルは utf8対応に成っていますでしょうか？

4. ボタンを押してエラーになった場合のログを添付いただけますか？
（抜粋で構いません）

**Comment by Manabu-H** [comment]
@akiko-pusu さん

早速のレスポンスありがとうございます。以下に回答いたします。

1.Redmineの環境はどのような状態でしょうか？
Redmine3.3のクリーンインストールでしょうか？
もしくは RedmineとIssue Template Pluginどちらもバージョンアップしながら継続して利用されている状況でしょうか。
⇒Redmineは旧バージョンからのアップレードです。Issue　Templete　Pluginは今回初めてです。


2.テンプレートを使わずに新規でチケットを作成することは可能でしょうか？
また、この場合に、テンプレートに登録しようとしたのと同じ内容をチケットに入力して作成することは可能でしょうか？
⇒可能です。同じ内容で試しましたが、問題なく作成できています。

3.MySQLのデータベース、テーブルは utf8対応に成っていますでしょうか？
⇒デフォルトのキャラクターセットがUTF8です。

4.ボタンを押してエラーになった場合のログを添付いただけますか？
 （抜粋で構いません）
⇒下記に添付します。
  Parameters: {"utf8"=>"?", "authenticity_token"=>"kH31mU9El73ELcxImnGLKeMvtAwFuowzGSiYAiS9DpU9oKf9o+4YSNytE8b1ryW2kHaG5KiLclRE7UVUVAxHBw==", "issue_template"=>{"title"=>"テストテンプレート１", "tracker_id"=>"5", "issue_title"=>"テストテン プレート１", "description"=>"テストテンプレート１", "note"=>"", "is_default"=>"0", "enabled"=>"0", "enabled_sharing"=>"0"}, "commit"=>"作成", "project_id"=>"sework_request", "id"=>"sework_request"}
  Current user: XXXXXXXX (id=736)
Completed 500 Internal Server Error in 61ms (ActiveRecord: 11.2ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Incorrect string value: '\xE3\x83\x86\xE3\x82\xB9...' for column 'title' at row 1: INSERT INTO `issue_templates` (`author_id`, `project_id`, `title`, `tracker_id`, `issue_title`, `description`, `note`, `created_on`, `updated_on`) VALUES (736, 237, 'テストテンプレート１', 5, 'テストテンプレート１', 'テストテンプレート１', '', '2017-03-06 13:39:35', '2017-03-06 13:39:35')):
  plugins/redmine_issue_templates/app/controllers/issue_templates_controller.rb:238:in `save_and_flash'
  plugins/redmine_issue_templates/app/controllers/issue_templates_controller.rb:76:in `new'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

以上、よろしくお願いいたします。

**Comment by akiko-pusu** [comment]
ありがとうございます。ではテンプレートの箇所ですね。
migrationは実施済みだと思いますが、MySQL から show create table issue_templates; の結果をつけていただくことは可能でしょうか？

> mysql> SHOW CReate TABLE issue_templates; \G 

のような感じです。
他のテーブルと文字コードの設定で差異がないかも確認いただけると助かります。

**Comment by Manabu-H** [comment]
mysql> SHOW CReate TABLE issue_templates; \G
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table           | Create Table |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| issue_templates | CREATE TABLE `issue_templates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `project_id` int(11) DEFAULT NULL,
  `tracker_id` int(11) NOT NULL,
  `author_id` int(11) NOT NULL,
  `note` varchar(255) DEFAULT NULL,
  `description` text,
  `enabled` tinyint(1) NOT NULL DEFAULT '0',
  `created_on` datetime DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `issue_title` varchar(255) DEFAULT NULL,
  `position` int(11) DEFAULT '1',
  `is_default` tinyint(1) DEFAULT '0',
  `enabled_sharing` tinyint(1) DEFAULT '0',
  `checklist_json` text,
  PRIMARY KEY (`id`),
  KEY `index_issue_templates_on_author_id` (`author_id`),
  KEY `index_issue_templates_on_project_id` (`project_id`),
  KEY `index_issue_templates_on_tracker_id` (`tracker_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

＞DEFAULT CHARSET=latin1

あれ？　utf8ではない？？

確認したところ、Redmineの環境が複数あるため、錯誤があったようです。
データベースとデーブルのデフォルトキャラセットはutf8ではありませんでした。

ここを修正したうえで、再度現象がでるか確認したいと思います。
少々お待ちいただければと思います。

**Comment by akiko-pusu** [comment]
情報ありがとうございます！
色々な事例があると問題の切り分けもしやすいですし、後からissueを投稿してくださる方にも大変有用な情報になります。
ご提供いただけること、大変助かります。

**Comment by Manabu-H** [comment]
mysql> ALTER TABLE issue_templates CONVERT TO CHARACTER SET utf8;
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql>  SHOW CReate TABLE issue_templates;
（略）
| issue_templates | CREATE TABLE `issue_templates` (
（略）
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |

上記のように該当テーブルのデフォルトキャラセットをutf8に変更して、
再度試したところ、問題なく日本語の入力ができるようになりました。

お騒がせしまして申し訳ありませんでした。
プラグイン自体のイシューではなかったですね；； 

ご対応いただきありがとうございました。大変助かりました。

**Comment by akiko-pusu** [comment]
@Manabu-H 
ご報告ありがとうございました、こちらも安心しました！
いろいろ情報をお寄せ頂けると、使ってくださる皆様のサポートにとってもたいへん助かります。

また、この度は拙いプラグインですがご利用検討くださってありがとうございます。
リクエストなどありましたら、日本語で問題ありませんので、ぜひお寄せくださいませ！
