### ISSUE TITLE
Italian translation sets en: language instead of it:

### ISSUE THREAD

**Issue by btassite** [akiko-pusu/redmine_issue_templates#87]
Second line of config/locales/it.yml is "en:" and should be changed to "it:", otherwise you will see Italian strings if your Redmine language is set to English.

In a running environment, restart the Redmine app to make the change active.

(plugin version 0.1.4)

**Comment by akiko-pusu** [comment]
oops!
@btassite Thank your for your point out my mistake, and I’ll update soon!

**Comment by akiko-pusu** [comment]
Thanks again, I’ve fixed and merged into master!
