### ISSUE TITLE
Set a global issue template as default

### ISSUE THREAD

**Issue by cancontrols** [akiko-pusu/redmine_issue_templates#90]
Hallo, 
First I would like to thank all people that brought the plugin to this excellent state. 

My feature-request: In Projects it is possible to set new issue templates as default for a tracker. Unfortunately this setting is not existing for global templates. Is it possible to include a "default-setting" in global template managment as well?

Best regards

Ulle

**Comment by akiko-pusu** [comment]
Thank you for your feedback! I’ve already received related requests before. 
Issue tracking would become more convenient if implement this, I’m going to try it!

**Comment by akiko-pusu** [comment]
Hi, @cancontrols and all.

Here is my idea to implement this feature.

Exp. There are 3 global issue templates for “Bug” tracker.
If one project, named A,  is configured to use 2 of 3 global templates for Bug which defined above and the project has 2 project local templates for Bug, the project can choose its own default template from both, protect local and global.  

On the other hand, another project choose 1 of 3 global templates for Bug, and has 1 project local template. And this another project can choose different global template as default from project A.

Do you think about? Or have any other ideas?
Let me know what you think.

**Comment by cancontrols** [comment]
Dear all,thank you for quick feedback. I think best way would be that user can define globally an issue-template and decide here1) This global issue template should be the default template for the choosen tracker2) This global issue template  should be valid for all projects (so we can get rid of selecting all projects seperatly if new are created).Afterwards the user should be able to override default template in local project settings.Your describe approach is very simmilar to my one except that I would like to define default behaviours for global issue templates as well since I would like avoid as much confiuration effort as possible (cmp point 2).Best regardsUlleingHi, @cancontrols and all.Here is my idea to implement this feature.Exp. There are 3 global issue templates for “Bug” tracker. If one project, named A, is configured to use 2 of 3 global templates for Bug which defined above and the project has 2 project local templates for Bug, the project can choose its own default template from both, protect local and global.On the other hand, another project choose 1 of 3 global templates for Bug, and has 1 project local template. And this another project can choose different global template as default from project A.Do you think about? Or have any other ideas? Let me know what you think.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by rakshazi** [comment]
Need it too :)

**Comment by akiko-pusu** [comment]
@cancontrols @rakshazi 
I’ve modified my code to be able to mark global issue tempates as default.
If projects have their own template and marked as default, the setting overrides global setting.

If you have time to review, could you please clone and try develop branch and check if it will be the expected behavior? 

> 2) This global issue template  should be valid for all projects (so we can get rid of selecting all projects seperatly if new are created).Afterwards the user should be able to override default template in local project settings.

2nd suggestion is not implemented yet.
I hope this request will be implemented in the next version. (Maybe v0.1.6)

**Comment by cancontrols** [comment]
Dear all,

 

I can confirm behavior as expected. Templates now could be set as default for a tracker. Good work!

Ulle

 

 

 

 <https://github.com/cancontrols> @cancontrols  <https://github.com/rakshazi> @rakshazi
I’ve modified my code to be able to mark global issue tempates as default.
If projects have their own template and marked as default, the setting overrides global setting.

If you have time to review, could you please clone and try develop branch and check if it will be the expected behavior?

2.	This global issue template should be valid for all projects (so we can get rid of selecting all projects seperatly if new are created).Afterwards the user should be able to override default template in local project settings.

2nd suggestion is not implemented yet.
I hope this request will be implemented in the next version. (Maybe v0.1.6)

**Comment by akiko-pusu** [comment]
@cancontrols, Thanks for your time to review above branch!
As requested at #61, I agree that it’s convenient for administrators to apply global template as default for every project where this plugin is enabled automatically, especially under large scaled Redmine.

So I’m going to add the feature to implement it.

**Comment by cancontrols** [comment]
Good morning,

two further helpful features:

1)      If I create a new ticket and I choose a template it would be great if I change afterwards the template the description field would be replaced. Right now I have first to push the erase button.

2)      In the admin-backend within the configuration view of a issue-template the option “select all” (projects) is located in the end of the project tree. In my case the list of projects is very long and would be much more comfortable to have the option on top.

 

Best regards

 

Ulle

**Comment by akiko-pusu** [comment]
Hi, I’m going to release v0.1.5, to implement some feature related for this request.
I’m not sure if the release meets your request enough, but please feel free to feedback!
