### ISSUE TITLE
ru translation

### ISSUE THREAD

**Issue by danaivehr** [akiko-pusu/redmine_issue_templates#95]
Hi!

Thank you a lot for your plugin. It seems to be very useful for our purposes.

I just added russian translation for all labels. It would be great if you will add it to your branch.

You can find ru.yml here: https://pastebin.com/EYWL0zD3

**Comment by akiko-pusu** [comment]
@danaivehr Thank you so much for your translation. I’m going to apply this soon.

BTW, do you have any problem when using Russian language,  related #74 ?
I can’t reproduce #74 ’s situation, but if you have saw the same trouble, this your update translation is quite helpful for me!

**Comment by danaivehr** [comment]
> BTW, do you have any problem when using Russian language, related #74 ?
No, nothing related for me, all is fine.

May be some kind of an environment issue, logs should be digged in i think.

The only one glitch i notice - template controls on New Issue form appears above "tracker" field for a moment, and then jump below "tracker" field. Is it a redmine plugin system architecture related problem or can be fixed?

**Comment by danaivehr** [comment]
> The only one glitch i notice - template controls on New Issue form appears above "tracker" field for a moment, and then jump below "tracker" field.

Created another issue for that: #96

**Comment by akiko-pusu** [comment]
Thanks for your support.
Now I’ve created Pull Request for this issue at
https://github.com/akiko-pusu/redmine_issue_templates/pull/97

If changed file is correct, I’m going to merge into master, thanks!

**Comment by akiko-pusu** [comment]
Merged into master.

**Comment by danaivehr** [comment]
Thanks!
